### ISSUE TITLE
Error / failed update after install (32 bit Windows 7)

### ISSUE THREAD

**Issue by janpop2017** [MiKTeX/miktex#188] opened 2018-08-29 20:49 UTC
**Please note: we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide all the required information.**

Checklist:
- [ X ] I am reporting a bug others will be able to reproduce
- [ X ] I have installed the latest MiKTeX updates
- [ X ] I have checked the MiKTeX log files

Please replace this section with the required information:
1. step-by-step reproduction instructions :
    Clean computer of all miktex related files and folders (incl. hidden)
    and clean Registry database of miktex entries
    and finally reboot
2. input files which are necessary to reproduce the bug :
    latest install file for MikTex 32 bit system    
3. your observations (command output, screenshots, ...) :
   see attached *.png files
4. relevant log file snippets :
    see attached *.log file
[miktex-install-and-update-log.txt](https://github.com/MiKTeX/miktex/files/2333737/miktex-install-and-update-log.txt)

![miktex-update-error-1](https://user-images.githubusercontent.com/31629038/44814576-7989db80-abdd-11e8-8b90-226a658fd71f.PNG)
![miktex-update-error-2](https://user-images.githubusercontent.com/31629038/44814577-7989db80-abdd-11e8-84d3-c48baade3e1b.PNG)

**Comment by edocevoli** [comment] 2018-08-29 21:15
Thank you. Which version of the installer (step 2) was used, i.e., what is the name of the installer executable?

**Comment by edocevoli** [comment] 2018-08-29 21:28
And please collect the log files in `C:\ProgramData\MiKTeX\2.9\miktex\log`.

**Comment by janpop2017** [comment] 2018-08-29 21:44
Install filename is : basic-miktex-2.9.6753.exe   (Windows 32 version from "All downloads, Basic")

Attached log files in log.zip :
[log.zip](https://github.com/MiKTeX/miktex/files/2333885/log.zip)

**Comment by edocevoli** [comment] 2018-08-29 21:51
Thank you. What is the current state of your MiKTeX setup? Can you start MiKTeX Console and check for updates?

**Comment by edocevoli** [comment] 2018-08-30 08:49
Duplicate of #187

**Closed** 2018-08-30 08:50 UTC
Labels: duplicate
