### ISSUE TITLE
A MiKTeX configuration file could not be loaded.

### ISSUE THREAD

**Issue by papadopalex** [MiKTeX/miktex#1385] opened 2023-10-07 13:37 UTC
Windows 10.  I updated to MiKTeX 23.9 two days ago.
I click to open MiKTeX Console and I get the message and error

```
A MiKTeX configuration file could not be loaded.
file="C:\Users\USERNAME\AppData\Local\Programs\MiKTeX\miktex/config\package-manifests.ini", 
line="80251", error="invalid value definition"
```
(I also see that TexStudio "does not find" certain packages, and cannot compile, which maybe is relevant.)

I found this file and opened it. Line "80251" is the very last line in the file (that just reads "desrip"). The last block in total there reads

```
[ean]
copyrightOwner=Petr Olšák
copyrightYear=1995
creator=mpc
ctanPath=/macros/generic/ean
descrip

```
And this is how the "package-manifests.ini" file ends. Now, I am just a user, knowing nothing about these things, but comparing it with the previous blocks in this file, it would appear that for some reason, this specific block (and perhaps what came after it) was somehow deleted/not downloaded/not installed, with the result that the "package-manifests.ini" file is not "complete". Is it possible then to find and download just the "package-manifets.ini" file in order to replace the existing one in my computer? Or recreate it somehow?

Thank you.

**Comment by edocevoli** [comment] 2023-10-07 13:50
Duplicate of #290

**Closed by edocevoli** 2023-10-07 13:50 UTC
