### ISSUE TITLE
Could not find script engine 'perl.exe' despite having perl installed and added to path

### ISSUE THREAD

**Issue by randomrevised** [MiKTeX/miktex#902] opened 2021-08-16 11:43 UTC
I just started using LaTeX on vscode, and whenever I try to compile any of my files, I keep getting the error message: `MiKTeX could not find the script engine 'perl.exe' which is required to execute 'latexmk'.` 

I have Strawberry perl installed on my system and have added both the bin folder and .exe to path, also tried moving the perl folder outside of the strawberry folder in case it wasn't clear enough for Windows to tell that perl was there.

I also ran checks to see if perl existed (which it did) multiple times and ran some tests from previous issues. Still no luck - it gives me the error message again.

Error logs are attached as well, but they just repeat the same lines of not being able to find perl.

All I want to do is to have an environment to work on LaTeX offline and I've only been running into issue after issue. I would really like to have this fixed. Thanks!

[latexmk.log](https://github.com/MiKTeX/miktex/files/6992050/latexmk.log)

**Comment by edocevoli** [comment] 2021-08-16 14:01
Duplicate of #...

**Closed by edocevoli** 2021-08-16 14:01 UTC
