### ISSUE TITLE
filehook package | update issue

### ISSUE THREAD

**Issue by cooch17** [MiKTeX/miktex#357] opened 2019-08-23 13:47 UTC
I recently tried updating the filehook package (from 0.5d to 0.5e), from a couple of different repos (same propblem, regardless of repo, so that isn't the issue). Basically, when you use MikTeX to install the filehook update, and then try to compile a file that requires it, an error gets thrown complaining that filehook.sty isn't found.  Sure enough, if you look in the filehook subdir, its empty.

So, something is wrong with the package update/installer for filehook. The workaround is to bypass the updater console in MikTeX, and download filehood from CTAN, and do a manual install from the command line. Refresh FNDB, and it all works. 

Just thought I'd pass this along to anyone use filehook (largely, people working with big documents where they're including a lot of .tex files -- say, chapters in a book or thesis).

**Comment by edocevoli** [comment] 2019-08-24 10:21
Duplicate of miktex/miktex-packaging#124

**Closed** 2019-08-24 10:22 UTC
Labels: duplicate
