### ISSUE TITLE
Miktex 20.10 windows silent uninstall issue

### ISSUE THREAD

**Issue by ub-jk** [MiKTeX/miktex#641] opened 2020-10-15 18:47 UTC
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

We are experiencing the following issue with MiKTeX 20.10:

Currently, we are successful doing a silent install of the new MiKTeX using the following command:
"basic-miktex-20.10-x64.exe" --shared --auto-install=yes --paper-size=Letter --unattended

For the uninstall:  In previous versions, we could download the Setup Utility for the corresponding installer (in this case x64) and run the following command from an elevated command prompt:
miktexsetup.exe --shared uninstall

However, it appears that this command is missing in the version on the site (the June 2020) version.  It did work in the previous version - however we cannot use that version as it will not work with the new version (only the 2.9 version).

Is it possible to get a newer version that will work with this new program version?  Eventually getting a command line uninstaller integrated with the installer would be nice but a fix for the current methodology would be greatly appreciated.

Sorry to bother people on this issue but it has a large impact on our silent install/uninstall processes for program deployment to a group of users.

**Comment by edocevoli** [comment] 2020-10-15 18:58
Duplicate of #596

**Closed by edocevoli** 2020-10-15 18:58 UTC
