### ISSUE TITLE
Miktex console won't start in administrator mode

### ISSUE THREAD

**Issue by pfedan** [MiKTeX/miktex#275] opened 2019-03-05 08:18 UTC
When I try to start `miktex-console.exe` and then klick on the button **Restart as administrator**, the console window closes itself, then I am asked for elevated permissions for `miktex-console_admin.exe` and then just nothing happens after klicking **Yes**.

I have installed Miktex using the installer: `basic-miktex-2.9.6942-x64.exe`in the folder `C:\TeX\Miktex` on a Windows 10 Pro x64 machine. 

Additionally, I noticed that I also cannot start `miktex-console_admin.exe` directly - same here: nothing happens after being asked for elevated permissions for `miktex-console_admin.exe` .

Finally, I tried to uninstall Miktex using the *Windows Uninstall-Manager*, also nothing happens after clicking on **uninstall**.

[miktex-console.log](https://github.com/MiKTeX/miktex/files/2929936/miktex-console.log)

**Comment by pfedan** [comment] 2019-03-05 08:55
Might be the same situation as it is in issue #239 here: 
https://github.com/MiKTeX/miktex/issues/239#issuecomment-467780488_

**Comment by pfedan** [comment] 2019-03-05 09:12
I can now confirm, that miktex-console is able to **Restart as administrator**, after I created  local user and ran the console from it. 

However, using a domain user, the console behaves as described above.

**Comment by edocevoli** [comment] 2019-03-05 14:34
Thank you. MiKTeX Console creates a lock file in the user's home directory. This seems to fail if a domain user is elevated.

Please try this:

1. Open a command-prompt window as an elevated domain user.
2. Run `echo %USERPROFILE%`
3. Run `echo test> "%USERPROFILE%\test.txt"

Does the third step succeed?

**Comment by pfedan** [comment] 2019-03-06 09:12
Following your steps (starting a `cmd.exe` instance as administrator, using my domain user account), I get the following output:

```
Microsoft Windows [Version 10.0.17134.590]
(c) 2018 Microsoft Corporation. Alle Rechte vorbehalten.

C:\Windows\system32>echo %USERPROFILE%
C:\Users\pfefferd

C:\Windows\system32>echo test> "%USERPROFILE%\test.txt"

C:\Windows\system32>
```
... and the file has been created as expected.

**Comment by pfedan** [comment] 2019-03-06 14:51
Posted a question on [SE:Superuser](https://superuser.com/questions/1411819/elevated-program-wont-start-when-invoked-by-domain-user).

**Comment by edocevoli** [comment] 2019-03-14 17:31
Duplicate of #239

**Closed** 2019-03-14 17:31 UTC
Labels: duplicate
