### ISSUE TITLE
MiKTeX not installing on MacOS 10.13.6

### ISSUE THREAD

**Issue by Barry-MacKichan** [MiKTeX/miktex#824] opened 2021-05-19 19:21 UTC
- [ ] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

I am trying to install MiKTeX on MacOS 10.13.6. When I run MiKTeX Console, it crashes. The relevant part of the dump seems to be:
"Dyld Error Message:
  Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/MiKTeX Console.app/Contents/MacOS/../miktex-lib/liblog4cxx.11.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib"

According to the prerequisites page, 10.13 is supported. Has something changed?

**Comment by edocevoli** [comment] 2021-05-19 19:38
Duplicate of #656

**Closed by edocevoli** 2021-05-19 19:38 UTC
