### ISSUE TITLE
"File is empty" error when opening MikTex on Mac BigSur

### ISSUE THREAD

**Issue by nkretzmann** [MiKTeX/miktex#758] opened 2021-03-21 18:19 UTC
- [ ] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)
Hi, MikTex has stopped working on my Mac (BigSur 11.2.3).
When I was managing some packages, it crashed, and everytime I try to open it, it shows a message "Sorry, but something went wrong". The details are "File is empty". I tried uninstall and install MikTex a couple of times, but it doesn't work.
How can I solve this?
<img width="394" alt="Captura de Tela 2021-03-21 às 14 56 52" src="https://user-images.githubusercontent.com/79531090/111916221-9d8dc080-8a58-11eb-8dfe-a28ff99fba0f.png">
<img width="456" alt="Captura de Tela 2021-03-21 às 15 15 50" src="https://user-images.githubusercontent.com/79531090/111916228-a1b9de00-8a58-11eb-95a9-cd109ea52ac4.png">

**Comment by edocevoli** [comment] 2021-03-21 18:25
Duplicate of #535

**Closed by edocevoli** 2021-03-21 18:25 UTC
