### ISSUE TITLE
MiKTeX Console Update Error: 500

### ISSUE THREAD

**Issue by jml111094** [MiKTeX/miktex#267] opened 2019-02-17 12:29 UTC
Hello,

I use MiKTeX on Windows and wanted to update my packages and ran the MiKTeX Console as admin, just as usual. But when I click 'Check for updates' the following error occurs:

Error response from server: 500
GENERAL MIKTEX INFORMATION
Date: 2019-02-17 13:32:32
MiKTeX: 2.9.6930
OS: Windows 10 Home, 64-bit, build 17763
SharedSetup: no
PathOkay: yes
LastUpdateCheck: not yet
LastUpdate: not yet
SystemAdmin: yes
RootPrivileges: no
AdminMode: no
Root0: E:\MiKTex 2.9\texmfs\config
Root1: E:\MiKTex 2.9\texmfs\data
Root2: E:\MiKTex 2.9\texmfs\install
UserInstall: E:\MiKTex 2.9\texmfs\install
UserConfig: E:\MiKTex 2.9\texmfs\config
UserData: E:\MiKTex 2.9\texmfs\data
CommonInstall: E:\MiKTex 2.9\texmfs\install
CommonConfig: E:\MiKTex 2.9\texmfs\config
CommonData: E:\MiKTex 2.9\texmfs\data
Invokers: non-existing

Warning: the following problems were detected:
  1: not yet checked for updates
  2: installation is not up-to-date

ERROR DETAILS
Program: E:\MiKTex 2.9\texmfs\install\miktex\bin\miktex-console.exe
Source: Libraries\MiKTeX\PackageManager\CurlWebSession.cpp:483
Error: Error response from server: 500
Details: 
  responseCode: 500

I tried reinstalling MiKTeX and even the portable version. Does somebody know how to fix it?

Thanks and regards!

**Comment by blizzard4591** [comment] 2019-02-17 12:35
The website and update servers are currently down, and it seems that the issue is being worked on.
Just check back later.

**Comment by edocevoli** [comment] 2019-02-17 14:30
Thank you, this has been fixed now.

**Closed by edocevoli** 2019-02-17 14:30 UTC
