### ISSUE TITLE
Miktex encountered an internal error after update

### ISSUE THREAD

**Issue by wolf01ms** [MiKTeX/miktex#113] opened 2018-04-15 10:01 UTC
After the last update with the Miktex Console an error occured when trying to open a file with Texstudio. The Error Text is:
_____________________________________
MiKTeX Problem Report
Message: MiKTeX encountered an internal error.
Data: 
Source: Libraries/MiKTeX/PackageManager/PackageManager.cpp
Line: 656
MiKTeX: 2.9
OS: Linux 4.13.0-38-generic #43~16.04.1-Ubuntu SMP Wed Mar 14 17:48:43 UTC 2018 x86_64
Invokers: .../cinnamon-launch/cinnamon/texstudio
SystemAdmin: no
Root0: /home/wolfgang/.miktex/texmfs/config
Root1: /home/wolfgang/.miktex/texmfs/data
Root2: /home/wolfgang/mytexmf
Root3: /home/wolfgang/.miktex/texmfs/install
Root4: /home/wolfgang/texmfs/config
Root5: /home/wolfgang/texmfs/data
Root6: /home/wolfgang/texmfs/install
UserInstall: /home/wolfgang/.miktex/texmfs/install
UserConfig: /home/wolfgang/.miktex/texmfs/config
UserData: /home/wolfgang/.miktex/texmfs/data
CommonInstall: /home/wolfgang/texmfs/install
CommonConfig: /home/wolfgang/texmfs/config
CommonData: /home/wolfgang/texmfs/data
___________________________________________________

After hitting ok, the automatic package installation opens with the message:

The required file miktex/config/unx/log5cxx.unx.xml is missing. It is part of the following package: miktex-config-2.9.

After hitting ok the package was not installed and the miktex internal error occured again.

I recognized that the package miktex-config-2.9 was labeled "obsolete" and erased by the last update. 

As a workaround I overwrote the directory /home/wolfgang/.miktex/texmfs/install/miktex/config with a copy out of a backup and then made a refresh of the filename database and the font map files.

**Comment by OctarineSorcerer** [comment] 2018-04-22 17:08
Seconded, I have the same issue. @wolf01ms, could you link me the backup, and say how to refresh the filename database/font map files?

**Comment by edocevoli** [comment] 2018-04-23 07:24
This is a duplicate of #109.

**Closed by edocevoli** 2018-04-23 07:24 UTC
Labels: duplicate
