### ISSUE TITLE
Error opening Miktek 20.6 on MacOS Catalina

### ISSUE THREAD

**Issue by doyindav** [MiKTeX/miktex#586] opened 2020-07-14 12:30 UTC
The Miktek console isn't opening on my mac. It shows "Error something went wrong" and when i open that it says "File is Empty"

- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

**Comment by edocevoli** [comment] 2020-07-14 12:38
Duplicate of #535

**Closed by edocevoli** 2020-07-14 12:38 UTC
Labels: duplicate
