### ISSUE TITLE
l3kernel pkg not installing - MD5 mismatch

### ISSUE THREAD

**Issue by tmnt93** [MiKTeX/miktex#812] opened 2021-05-09 22:04 UTC
The CabMD5 and related manifest information found on the current l3kernel package in the repositories does not match the information in the mpm.ini file. The l3kernel was recently updated on 05-07-2021. I believe the l3kernel manifest information in the mpm.ini file was pegged to the 02-19-2021 version.

**Comment by tmnt93** [comment] 2021-05-09 22:35
expectedMD5="24c14f15da8b454a939c057af8a15990", actualMD5="4dab8d4ccc66cf594cfab7c51867ab2d", package="l3kernel", arhiveFile="/tmp/mik5KWu4Z"

**Comment by edocevoli** [comment] 2021-05-10 07:03
Duplicate of #809

**Closed by edocevoli** 2021-05-10 07:03 UTC
