### ISSUE TITLE
Installing miktex on Ubuntu 20.04

### ISSUE THREAD

**Issue by ThamuMnyulwa** [MiKTeX/miktex#624] opened 2020-09-18 10:08 UTC
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

I am trying to install Miketex onto a computer running Ubuntu 20.04.

    Distributor ID:	Ubuntu
    Description:	Ubuntu 20.04.1 LTS
    Release:	20.04
    Codename:	focal

I have followed the instructions from [Miketex](https://miktex.org/howto/install-miktex-unx), but come up with the following error when I try to run the <code>sudo apt-get update</code> line:

    N: Skipping acquisition of configured file 'universe/binary-i386/Packages', as repository 
    'http://miktex.org/download/ubuntu bionic InRelease' doesn't support architecture 'i386'

I managed to find a solution to this (I think) in a [Github repository](https://github.com/MiKTeX/miktex/issues/48) where someone said:

> On 64 bit machine, I was getting same issue. I solved it by replacing the contents of miktek.list with the following line:
deb [arch=amd64] http://miktex.org/download/ubuntu xenial universe.

My current file (which has the following location <code> /etc/apt/sources.list.d/miketex.list
 </code>) has the following line that I would like to replace:

    deb http://miktex.org/download/ubuntu bionic universe

My problem is that I cannot replace the line in the file and save. The file <code>miketex.list</code> is a read-only file. I did find a similar question on replacing lines in a file using nano ([AskUbuntu: Unable to edit /etc/apt/sources.list file](https://askubuntu.com/questions/332669/unable-to-edit-etc-apt-sources-list-file)), however I could not implement the solution suggested using nano. I would like to ask how should I use this to replace the line in the sources list file to the desired <code>deb [arch=amd64] http://miktex.org/download/ubuntu xenial universe</code> .

After running the line in nano. 

    sudo nano /etc/apt/sources.list.d/miketex.list

and get the following output:

    GNU nano 4.8         /etc/apt/sources.list.d/miketex.list

followed by the nano instructions. I am not sure how to replace the desired line in <code>miketex.list</code>.

*This question has been cross-posted by me on Askubuntu.*

**Comment by edocevoli** [comment] 2020-09-18 17:54
You have to specify the architecture when registering the the repository.
Please see #567 for a possible workaround.

**Comment by edocevoli** [comment] 2020-09-18 17:54
Duplicate of #567

**Closed by edocevoli** 2020-09-18 17:54 UTC
