### ISSUE TITLE
[Pre-release] Possible bug(s) in MiKTeX component or fbb/ETbb packages resulting in incompatibilities with other packages

### ISSUE THREAD

**Issue by pdsz** [MiKTeX/miktex#587] opened 2020-07-14 17:08 UTC
In current (2020-07-14) MiKTeX pre-release, `ETbb` package with option `swashQ` seems to be incompatible with `\textit` (see MWE 1) and both `fbb` and `ETbb` do not work with footnotes of `footmisc` package with option `symbol` (see MWE 2).

This is related to [a TEX.SX question](https://tex.stackexchange.com/q/553429). As advised in comments to this question, I report this also here as an issue.

I attach MWEs to reproduce the errors, command outputs, configuration report and pdflatex logs:
[MWEs.zip](https://github.com/MiKTeX/miktex/files/4920146/MWEs.zip)
[Command output (MWE 1).txt](https://github.com/MiKTeX/miktex/files/4920148/Command.output.MWE.1.txt)
[Command output (MWE 2).txt](https://github.com/MiKTeX/miktex/files/4920150/Command.output.MWE.2.txt)
[miktex-report.txt](https://github.com/MiKTeX/miktex/files/4920151/miktex-report.txt)
[pdflatex (MWE 1).log](https://github.com/MiKTeX/miktex/files/4920153/pdflatex.MWE.1.log)
[pdflatex (MWE 2).log](https://github.com/MiKTeX/miktex/files/4920154/pdflatex.MWE.2.log)

### MWE 1:

```
\documentclass{article}

%\usepackage[swashQ]{fbb} % No error.
%\usepackage{ETbb} % No error.
\usepackage[swashQ]{ETbb} % Error when using with \textit{…}.

\begin{document}
	Quest. % No error.
	\textit{Test}. % Error when using with \usepackage[swashQ]{ETbb}.
\end{document}
```

### MWE 2:

```
\documentclass{article}

\usepackage[symbol]{footmisc}

\usepackage{fbb} % Error when using with \footnote{…} of footmisc with option symbol.
%\usepackage{ETbb} % Error when using with \footnote{…} of footmisc with option symbol.

\begin{document}
	Test% No error.
	\footnote{Test.}. % Error for \usepackage{fbb} or \usepackage{ETbb}.
\end{document}
```

### Command outputs:

```
Process started: pdflatex.exe -synctex=1 -interaction=nonstopmode "MWE ⟨number⟩".tex

Sorry, but pdflatex.exe did not succeed. The log file hopefully contains the information to get MiKTeX going again: C:\Users\⟨user⟩\AppData\Local\MiKTeX\2.9\miktex\log\pdflatex.log

Process exited with error(s)
```

**Comment by edocevoli** [comment] 2020-07-14 20:27
Duplicate of #568 

Please note: The pre-release version is from 2020-06-23. That is, it is older than the released version (2020-06-30). I would recommend that you switch to the release version where the reported bug isfixed.

**Closed by edocevoli** 2020-07-14 20:27 UTC
Labels: duplicate
