### ISSUE TITLE
"varioref" missing documentation

### ISSUE THREAD

**Issue by BeerStud** [MiKTeX/miktex#866] opened 2021-07-05 16:39 UTC
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

Environment:
TeXstudio: 3.1.2 (git 3.1.2)
Qt: 5.15.2, compiled with Qt 5.15.2 R
OS: Windows 10 Pro - 64 bit
TeX distribution: Miktex

Expected behavior:
When I click on "varioref" in "\usepackage[nospace]{varioref}", I expect to see the documentation.

Actual behavior:
I receive this error message:
Process started: texdoc.exe --list-only varioref
Documentation for varioref could not be found.
Process exited normally

How to reproduce:
See "Expected Behavior"

Apparently, the documentation is not available for "varioref".

**Comment by edocevoli** [comment] 2021-07-05 19:03
Duplicate of #863

**Closed by edocevoli** 2021-07-05 19:03 UTC
