### ISSUE TITLE
A Miktex configuration file could not be loaded

### ISSUE THREAD

**Issue by KostMT** [MiKTeX/miktex#402] opened 2019-10-25 12:31 UTC
Hi there, 

I had installed Miktex a couple of weeks ago, and started using it now. I had encountered a problem after installing Miktex where it couldn't connect to the repository, but after re-installing, it seemed to work fine. However, once I try to compile for the first time in this computer via TexStudio a file that works on another pc, I get an error on my TexStudio, which when I open the Miktex Console to check I get the following:

`A MiKTeX configuration file could not be loaded. file="C:\Program Files (x86)\MiKTeX 2.9\miktex/config\package-manifests.ini", line="159496", error="invalid value definition"`

The line 159496 in the package-manifests is:
`run[]=texmf/tex/generic/pgfornament/vectorian/vectorian35.pgf
` 

Going to the diagnose tab I have the following that may help diagnose the issue:

```
Date: 2019-10-25 13:10:29
MiKTeX: 2.9.7200
OS: Windows 10 Enterprise, 64-bit, build 17763
SharedSetup: yes
LinkTargetDirectory: C:\Program Files (x86)\MiKTeX 2.9\miktex\bin
PathOkay: yes
LastUpdateCheckAdmin: 2019-10-25 11:08:44
LastUpdateAdmin: not yet
SystemAdmin: yes
RootPrivileges: yes
AdminMode: yes
Root0: C:\ProgramData\MiKTeX\2.9
Root1: C:\Program Files (x86)\MiKTeX 2.9
CommonInstall: C:\Program Files (x86)\MiKTeX 2.9
CommonConfig: C:\ProgramData\MiKTeX\2.9
CommonData: C:\ProgramData\MiKTeX\2.9
```

Attached you can also find the relevant log files.
[initexmf_admin.log](https://github.com/MiKTeX/miktex/files/3771971/initexmf_admin.log)
[miktex-console_admin.log](https://github.com/MiKTeX/miktex/files/3771973/miktex-console_admin.log)

I would like to include a more specific procedure to reproduce the error, however I really havent done anything special other than installing, uninstalling, and re-installing. So I suspect this might be causing it in a way...

Thanks for your help in advance,

KMT.

P.S.

Even though I have been using LaTeX for some years now, I have never really troubleshooted, so I am 'a basic user'. Therefore I appologise in advance if I have to ask you to clarify, or if I inadvertedly did not include some information that I should have.

**Comment by edocevoli** [comment] 2019-10-25 13:17
Duplicate of #290

**Closed by edocevoli** 2019-10-25 13:17 UTC
