### ISSUE TITLE
Peer certificate cannot be authenticated with given CA certificates

### ISSUE THREAD

**Issue by hrrichardson** [MiKTeX/miktex#180] opened 2018-08-23 19:26 UTC
Checklist:
- [ x] I am reporting a bug others will be able to reproduce
- [ x] I have installed the latest (version of) MiKTeX 
- [ x] I have checked the MiKTeX log files

Hi,

1. I have installed basic-miktex-2.9.6753-x64 onto my Windows 7 machine. After install the Miktex console notifies me of an error that "something went wrong while checking for updates" and when I select error details I see this message "Peer certificate cannot be authenticated with given CA certificates"
 
2. I am not sure how this error can be reproduced, I did see a similar post about it however there was not a clear solution proposed. I have been hunting through the services on my machine but have yet to find what is causing the issue.
https://github.com/MiKTeX/miktex/issues/118

3. Screenshot of error
![miktex_error](https://user-images.githubusercontent.com/42618536/44547302-7e2b2d00-a6cf-11e8-8701-94be018d3607.png)

4. Log Files are below
[initexmf.log](https://github.com/MiKTeX/miktex/files/2315853/initexmf.log)
[miktex-console.log](https://github.com/MiKTeX/miktex/files/2315854/miktex-console.log)
[miktex-fc-cache.log](https://github.com/MiKTeX/miktex/files/2315855/miktex-fc-cache.log)
[mkfntmap.log](https://github.com/MiKTeX/miktex/files/2315856/mkfntmap.log)
[mpmcli.log](https://github.com/MiKTeX/miktex/files/2315857/mpmcli.log)

Thank you for the help, 
Heather

**Comment by edocevoli** [comment] 2018-08-23 21:47
Duplicate of #118

**Comment by edocevoli** [comment] 2018-08-23 21:52
I am closing the issue because it contains no new information, i.e., #118 remains the master ticket for this issue.

**Closed by edocevoli** 2018-08-23 21:52 UTC
