### ISSUE TITLE
Why latex does not tell me which command is undefined?

### ISSUE THREAD

**Issue by evandrocoan** [MiKTeX/miktex#292] opened 2019-04-21 19:36 UTC
https://tex.stackexchange.com/questions/485830/why-latex-does-not-tell-me-which-command-is-undefined?noredirect=1#comment1228734_485830

May be a duplicate of (https://github.com/MiKTeX/miktex/issues/181 Make file-line-error more talkative)?

**Comment by edocevoli** [comment] 2019-04-21 20:48
Yes, this is a duplicate.

**Comment by edocevoli** [comment] 2019-04-21 20:48
Duplicate of #181

**Closed** 2019-04-21 20:48 UTC
Labels: duplicate
