### ISSUE TITLE
[MiKTeX Portable] How do you add a TEXMF root directory?

### ISSUE THREAD

**Issue by petiard** [MiKTeX/miktex#159] opened 2018-07-08 13:25 UTC
Checklist:
- [x] I am reporting a bug others will be able to reproduce
- [x] I have installed the latest MiKTeX updates
- [x] I have checked the MiKTeX log files

1. in MiKTeX console, Settings, I add a new TEXMF root directory, say localtexmf, which is TDS compliant
2. I see that directory in the list of TEXMF root directories
3. Then, I quit MiKTeX console and when I restart the console, I don't see localtexmf in the list ???

**Comment by edocevoli** [comment] 2018-07-09 17:50
Duplicate of #66

**Closed by edocevoli** 2018-07-09 17:50 UTC
