### ISSUE TITLE
Error during update

### ISSUE THREAD

**Issue by communistkiro** [MiKTeX/miktex#201] opened 2018-09-28 21:21 UTC
Checklist:
- [no] I am reporting a bug others will be able to reproduce
- [?] I have installed the latest MiKTeX updates- _I'm unsure as to how, currently I have MiKTeX Console 2.9.6809_
- [X] I have checked the MiKTeX log files- https://pastebin.com/cyj5UBnU, this doesn't tell me much, says sth about a log, but where can I find it?

Please replace this section with the required information:
1. I wanted to update installed packages, I did so and at the very end I had an error, although the packages were indeed updated on repeated clicking of 'Check for updates'
2. Error and error details- 
![capture](https://user-images.githubusercontent.com/2643286/46233993-1d99aa80-c375-11e8-9c29-9534c1f78333.PNG)
3. Can't repeat the error during updating, however, after every attempted build (which fails if no temp files exist) I get the following-
![capture1](https://user-images.githubusercontent.com/2643286/46234204-da8c0700-c375-11e8-9291-554257d24a14.PNG)

Before update, building worked, be it latex, xelatex, pfdlatex, now I get fatal error re:sth not found in the dynamic link library MiKTeX209-core.dll

**Comment by edocevoli** [comment] 2018-09-29 07:49
Duplicate of #184

**Closed by edocevoli** 2018-09-29 07:49 UTC
