### ISSUE TITLE
Biber not working with Biblatex after the update - Mac OS/MikTex/TexStudio

### ISSUE THREAD

**Issue by AleksejsN** [MiKTeX/miktex#1057] opened 2022-02-20 13:06 UTC
- [ X] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

I have updated all my Latex software, and basically, nothing is working.

Software versions are: 
TeXstudio 4.2.1 (git 4.2.1); 
Using Qt Version 6.2.2, compiled with Qt 6.2.2 R; 
MiKTeX 22.1; 
Mac OS Monterey 12.2.1;

So far I have tried deleting all apps, their related directories and files + clean install. Admin \ user versions of the MikTex made no difference. Updating MikTex on the user or admin-level didn't help either. Users from StackExchange suggest that the MikTeX Biber package for Mac OS hasn't been updated.

```
   Process started: biber "business report"
    
    INFO - This is Biber 2.16
    INFO - Logfile is 'business report.blg'
    INFO - Reading 'business report.bcf'
    ERROR - Error: Found biblatex control file version 3.8, expected version 3.7.
    This means that your biber (2.16) and biblatex (3.17) versions are incompatible.
    See compat matrix in biblatex or biber PDF documentation.
    INFO - ERRORS: 1
    Process exited with error(s)

        miktex-mf: MiKTeX encountered an internal error. miktex-mf: Data: path="Oenology/Latex/Business report" Sorry, but miktex-mf did not succeed. libc++abi: terminating with uncaught exception of type MiKTeX::Core::MiKTeXException: /Users/mik/work3/MiKTeX/mik
    tex/Libraries/MiKTeX/App/app.cpp:1138: internal error
    Sorry, but miktex-makepk did not succeed. The log file hopefully contains the information to get MiKTeX going again: /Users/AN/Library/Application Support/MiKTeX/texmfs/data/miktex/log/miktex-makepk.log
    Process exited with error(s)

miktex-mf: MiKTeX encountered an internal error. miktex-mf: Data
: path="Oenology/Latex/Business report" Sorry, but miktex-mf did not succeed. libc++abi: terminating with uncaught exception of type MiKTeX::Core::MiKTeXException: /Users/mik/work3/MiKTeX/mik
tex/Libraries/MiKTeX/App/app.cpp:1138: internal error

Sorry, but miktex-makepk did not succeed. The log file hopefully contains the information to get MiKTeX going again: /Users/AN/Library/Application Support/MiKTeX/texmfs/data/miktex/log/miktex-makepk.log
Process exited with error(s)

```

I have attached the log file to this post.

[miktex-makepk.log](https://github.com/MiKTeX/miktex/files/8104010/miktex-makepk.log)

**Comment by edocevoli** [comment] 2022-02-20 13:09
Seems to be a duplicate of:
https://github.com/MiKTeX/miktex-packaging/issues/270

**Closed by edocevoli** 2022-02-20 13:09 UTC
