### ISSUE TITLE
The remote package repository is outdated. You have to choose another repository.

### ISSUE THREAD

**Issue by mwissing** [MiKTeX/miktex#332] opened 2019-06-20 13:25 UTC
MiKTeX just worked fine, got this problem today:
"The remote package repository is outdated. You have to choose another repository."
Tried other repository's. Same problem. Reinstalling didn't fix this.

GENERAL MIKTEX INFORMATION
Date: 2019-06-20 15:23:21
MiKTeX: 2.9.7050
OS: Windows 10 Enterprise, 64-bit, build 17134
SharedSetup: no
LinkTargetDirectory: C:\Users\mwissing\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64
PathOkay: yes
LastUpdateCheck: not yet
LastUpdate: not yet
SystemAdmin: yes
RootPrivileges: yes
AdminMode: no
Root0: C:\Users\mwissing\AppData\Roaming\MiKTeX\2.9
Root1: C:\Users\mwissing\AppData\Local\MiKTeX\2.9
Root2: C:\Users\mwissing\AppData\Local\Programs\MiKTeX 2.9
Root3: C:\ProgramData\MiKTeX\2.9
Root4: C:\Program Files\MiKTeX 2.9
UserInstall: C:\Users\mwissing\AppData\Local\Programs\MiKTeX 2.9
UserConfig: C:\Users\mwissing\AppData\Roaming\MiKTeX\2.9
UserData: C:\Users\mwissing\AppData\Local\MiKTeX\2.9
CommonInstall: C:\Program Files\MiKTeX 2.9
CommonConfig: C:\ProgramData\MiKTeX\2.9
CommonData: C:\ProgramData\MiKTeX\2.9
Invokers: non-existing/explorer

Warning: the following problems were detected:
  1: Never checked for updates.

ERROR DETAILS
Program: C:\Users\mwissing\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\miktex-console.exe
Source: Libraries\MiKTeX\PackageManager\RestRemoteService.cpp:287
Error: The remote package repository is outdated. You have to choose another repository.
Details: 
  url: ftp://ftp.rrzn.uni-hannover.de/pub/mirror/tex-archive/systems/win32/miktex/tm/packages/

**Comment by edocevoli** [comment] 2019-06-20 13:57
Thank you. This will be fixed.

**Closed by edocevoli** 2019-06-20 13:57 UTC

**Comment by edocevoli** [comment] 2019-06-20 14:10
Cannot reproduce your issue. Please select another repository (as the error message suggests).
