### ISSUE TITLE
MikTeX on Fedora 32. Problem.

### ISSUE THREAD

**Issue by jpcmborges** [MiKTeX/miktex#616] opened 2020-09-10 18:32 UTC
[jborges @ joaoborges ~] $ sudo ln -s /usr/lib64/libmpfr.so.6 /usr/lib64/libmpfr.so.4
[sudo] password for jborges:
ln: failed to create symbolic link '/usr/lib64/libmpfr.so.4': The file exists
[jborges @ joaoborges ~] $ sudo rpm --import "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xD6BC243565B2087BC3F897C9277A7293F59E4889"
[jborges @ joaoborges ~] $ wget "https://miktex.org/download/fedora/30/miktex-2.9.7400-1.fc30.x86_64.rpm"
--2020-09-10 19: 22: 26-- https://miktex.org/download/fedora/30/miktex-2.9.7400-1.fc30.x86_64.rpm
Resolving miktex.org (miktex.org) ... 5.175.24.104
Calling miktex.org (miktex.org) | 5.175.24.104 |: 443 ... connected.
HTTP request sent, waiting for response ... 302 Found
Location: https://ftp.eq.uc.pt/software/TeX/systems/win32/miktex/setup/rpm/fedora/30/miktex-2.9.7400-1.fc30.x86_64.rpm [below]
--2020-09-10 19: 22: 26-- https://ftp.eq.uc.pt/software/TeX/systems/win32/miktex/setup/rpm/fedora/30/miktex-2.9.7400- 1.fc30.x86_64.rpm
To resolve ftp.eq.uc.pt (ftp.eq.uc.pt) ... 193.137.214.36
Connecting to ftp.eq.uc.pt (ftp.eq.uc.pt) | 193.137.214.36 |: 443 ... connected.
HTTP request sent, waiting for response ... 200 OK
Size: 20811036 (20M) [application / x-redhat-package-manager]
Recording at: "miktex-2.9.7400-1.fc30.x86_64.rpm"

miktex-2.9.7400-1.fc30.x 100% [=================================>] 19 , 85M 12.7MB / s in 1.6s

2020-09-10 19:22:28 (12.7 MB / s) - "miktex-2.9.7400-1.fc30.x86_64.rpm" recorded [20811036/20811036]

[jborges @ joaoborges ~] $ sudo rpm -i --nodeps miktex-2.9.7400-1.fc30.x86_64.rpm
the /usr/share/man/man5/updmap.cfg.5.gz file from the miktex-2.9.7400-1.fc30.x86_64 installation conflicts with the texlive-tetex-7: 20190410-12 package file. fc32.noarch

**Comment by edocevoli** [comment] 2020-09-10 19:07
Duplicate of #615

**Closed by edocevoli** 2020-09-10 19:07 UTC
