### ISSUE TITLE
latexindent shim points to the package's perl script, not standalone exe

### ISSUE THREAD

**Issue by raikesy** [MiKTeX/miktex#194] opened 2018-09-12 17:02 UTC
**Please note: we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide all the required information.**

Checklist:
- [ x ] I am reporting a bug others will be able to reproduce
- [ x ] I have installed the latest MiKTeX updates
- [ x ] I have checked the MiKTeX log files

### The Issue
- Miktex packages latexindent but it currently fails out of the box on Windows
- This is because, as a perl script, a perl installation is required
- This is not unique to latexindent, it is also true for latexmk
- The difference is that:
  1. latexindent also required a certain perl module to be installed `Log::Log4perl`. Installing a perl module is significantly more involved than just installing perl. [Relevant StackExchange](https://tex.stackexchange.com/questions/445521/latexindent-cant-locate-log-log4perl-pm-in-inc-you-may-need-to-install-the-l)
  2. The latexindent package actually already comes with a standalone exe file which just runs out of the box on Windows

### Suggested fix
Miktex should point its latexindent.exe shim (in the bin directory) to the standalone exe rather than the perl script which requires significant effort to get running. This would allow latexindent to run out of the box on Windows.

I will post this on miktex-packaging too as I don't know which scope it falls under.

**Comment by edocevoli** [comment] 2018-09-12 18:05
Duplicate of MiKTeX/miktex-packaging#50

**Closed by edocevoli** 2018-09-12 18:05 UTC
