### ISSUE TITLE
Unable to update on Windows do to "l3backend" issue

### ISSUE THREAD

**Issue by johnsutor** [MiKTeX/miktex#810] opened 2021-05-09 17:42 UTC
On Windows 10, I receive the issue "The operation could not be completed because a required file failed verification.", more specifically, the error log shows 

package="l3backend", arhiveFile="C:\Users\johns\AppData\Local\Temp\mikE3EC.tmp", expectedMD5="47f7d88feead7c8108a86ad8ec5d0422", actualMD5="c42606db1554c2f3248bdd436447cdd6"

Here are the logs:

2021-05-09 13:31:48,264-0400 INFO  main - starting: MiKTeX Console 4.2 (MiKTeX 21.2)
2021-05-09 13:31:49,704-0400 WARN  miktex-console.packagemanager - dependancy problem: tools is required by _miktex-latex-required
2021-05-09 13:31:49,704-0400 WARN  miktex-console.packagemanager - dependancy problem: miktex-doc-2.9 is required by _miktex-packages-2.9
2021-05-09 13:34:31,809-0400 INFO  main - starting: MiKTeX Console 4.2 (MiKTeX 21.2)
2021-05-09 13:34:31,846-0400 INFO  miktex-console.core - start process: pdftex --miktex-disable-installer --miktex-disable-maintenance --miktex-disable-diagnose --version
2021-05-09 13:34:33,443-0400 WARN  miktex-console.packagemanager - dependancy problem: tools is required by _miktex-latex-required
2021-05-09 13:34:33,443-0400 WARN  miktex-console.packagemanager - dependancy problem: miktex-doc-2.9 is required by _miktex-packages-2.9
2021-05-09 13:34:36,429-0400 INFO  mainwindow - checking for updates...
2021-05-09 13:34:36,435-0400 INFO  miktex-console.packagemanager - searching for updateable packages
2021-05-09 13:34:36,445-0400 INFO  miktex-console.packagemanager - going to download https://api2.miktex.org/hello
2021-05-09 13:34:37,003-0400 INFO  miktex-console.packagemanager - going to download https://api2.miktex.org/repositories?&releaseState=Stable&orderBy=ranking&take=1
2021-05-09 13:34:37,135-0400 INFO  mainwindow - downloading https://ctan.mirrors.hoobly.com/systems/win32/miktex/tm/packages/miktex-zzdb3-2.9.tar.lzma...
2021-05-09 13:34:37,136-0400 INFO  miktex-console.packagemanager - going to download https://ctan.mirrors.hoobly.com/systems/win32/miktex/tm/packages/miktex-zzdb3-2.9.tar.lzma
2021-05-09 13:34:37,519-0400 INFO  mainwindow - 1.19 MB, 24.82 Mbit/s
2021-05-09 13:34:38,588-0400 INFO  mainwindow - updating package manifests (C:\Users\johns\AppData\Local\Programs\MiKTeX\miktex/config\package-manifests.ini)...
2021-05-09 13:34:39,771-0400 INFO  mainwindow - installed 3935 package manifests
2021-05-09 13:34:39,772-0400 INFO  mainwindow - visiting repository https://ctan.mirrors.hoobly.com/systems/win32/miktex/tm/packages/...
2021-05-09 13:34:39,772-0400 INFO  mainwindow - repository type: remote package repository
2021-05-09 13:34:39,772-0400 INFO  mainwindow - loading package repository manifest...
2021-05-09 13:34:39,773-0400 INFO  mainwindow - downloading https://ctan.mirrors.hoobly.com/systems/win32/miktex/tm/packages/miktex-zzdb1-2.9.tar.lzma...
2021-05-09 13:34:39,773-0400 INFO  miktex-console.packagemanager - going to download https://ctan.mirrors.hoobly.com/systems/win32/miktex/tm/packages/miktex-zzdb1-2.9.tar.lzma
2021-05-09 13:34:40,008-0400 INFO  mainwindow - 0.21 MB, 7.12 Mbit/s
2021-05-09 13:34:41,010-0400 WARN  miktex-console.packagemanager - dependancy problem: tools is required by _miktex-latex-required
2021-05-09 13:34:41,010-0400 WARN  miktex-console.packagemanager - dependancy problem: miktex-doc-2.9 is required by _miktex-packages-2.9
2021-05-09 13:34:42,811-0400 INFO  mainwindow - package repository digest: b2158409da406b706beff7147014b152
2021-05-09 13:34:50,768-0400 INFO  mainwindow - found 102 updates
2021-05-09 13:34:50,784-0400 INFO  miktex-console.core - start process: pdftex --miktex-disable-installer --miktex-disable-maintenance --miktex-disable-diagnose --version
2021-05-09 13:35:06,085-0400 INFO  miktex-console.packagemanager - going to download https://api2.miktex.org/repositories?&releaseState=Stable
2021-05-09 13:35:14,523-0400 INFO  mainwindow - installing updates...
2021-05-09 13:35:14,525-0400 INFO  miktex-console.packagemanager - going to download https://api2.miktex.org/repositories/4a555517cb5ecf2c0d2bd110f5a4e10e
2021-05-09 13:35:15,059-0400 INFO  mainwindow - starting package maintenance...
2021-05-09 13:35:15,059-0400 INFO  mainwindow - installation directory: C:\Users\johns\AppData\Local\Programs\MiKTeX
2021-05-09 13:35:15,059-0400 INFO  mainwindow - package repository: https://ctan.math.illinois.edu/systems/win32/miktex/tm/packages/
2021-05-09 13:35:15,188-0400 INFO  mainwindow - package repository digest: b2158409da406b706beff7147014b152
2021-05-09 13:35:15,189-0400 INFO  mainwindow - going to download 42956338 bytes
2021-05-09 13:35:15,189-0400 INFO  mainwindow - going to install 1746 file(s) (102 package(s))
2021-05-09 13:35:15,538-0400 INFO  miktex-console.packagemanager - installing package babel
2021-05-09 13:35:15,539-0400 INFO  mainwindow - downloading https://ctan.math.illinois.edu/systems/win32/miktex/tm/packages/babel.tar.lzma...
2021-05-09 13:35:15,539-0400 INFO  miktex-console.packagemanager - going to download https://ctan.math.illinois.edu/systems/win32/miktex/tm/packages/babel.tar.lzma
2021-05-09 13:35:16,595-0400 INFO  mainwindow - 1.69 MB, 12.84 Mbit/s
2021-05-09 13:35:16,939-0400 INFO  mainwindow - extracting files from babel.tar.lzma...
2021-05-09 13:35:17,921-0400 INFO  miktex-console.packagemanager - installing package csplain
2021-05-09 13:35:17,921-0400 INFO  mainwindow - downloading https://ctan.math.illinois.edu/systems/win32/miktex/tm/packages/csplain.tar.lzma...
2021-05-09 13:35:17,921-0400 INFO  miktex-console.packagemanager - going to download https://ctan.math.illinois.edu/systems/win32/miktex/tm/packages/csplain.tar.lzma
2021-05-09 13:35:18,676-0400 INFO  mainwindow - 1.72 MB, 18.29 Mbit/s
2021-05-09 13:35:18,741-0400 INFO  mainwindow - extracting files from csplain.tar.lzma...
2021-05-09 13:35:18,945-0400 INFO  miktex-console.packagemanager - installing package graphics-def
2021-05-09 13:35:18,946-0400 INFO  mainwindow - downloading https://ctan.math.illinois.edu/systems/win32/miktex/tm/packages/graphics-def.tar.lzma...
2021-05-09 13:35:18,946-0400 INFO  miktex-console.packagemanager - going to download https://ctan.math.illinois.edu/systems/win32/miktex/tm/packages/graphics-def.tar.lzma
2021-05-09 13:35:18,993-0400 INFO  mainwindow - 0.01 MB, 1.93 Mbit/s
2021-05-09 13:35:19,007-0400 INFO  mainwindow - extracting files from graphics-def.tar.lzma...
2021-05-09 13:35:19,029-0400 INFO  miktex-console.packagemanager - installing package hyperref
2021-05-09 13:35:19,029-0400 INFO  mainwindow - downloading https://ctan.math.illinois.edu/systems/win32/miktex/tm/packages/hyperref.tar.lzma...
2021-05-09 13:35:19,029-0400 INFO  miktex-console.packagemanager - going to download https://ctan.math.illinois.edu/systems/win32/miktex/tm/packages/hyperref.tar.lzma
2021-05-09 13:35:20,289-0400 INFO  mainwindow - 3.82 MB, 24.30 Mbit/s
2021-05-09 13:35:20,336-0400 INFO  mainwindow - extracting files from hyperref.tar.lzma...
2021-05-09 13:35:20,599-0400 INFO  miktex-console.packagemanager - installing package hyph-utf8
2021-05-09 13:35:20,599-0400 INFO  mainwindow - downloading https://ctan.math.illinois.edu/systems/win32/miktex/tm/packages/hyph-utf8.tar.lzma...
2021-05-09 13:35:20,599-0400 INFO  miktex-console.packagemanager - going to download https://ctan.math.illinois.edu/systems/win32/miktex/tm/packages/hyph-utf8.tar.lzma
2021-05-09 13:35:21,215-0400 INFO  mainwindow - 1.88 MB, 24.41 Mbit/s
2021-05-09 13:35:21,427-0400 INFO  mainwindow - extracting files from hyph-utf8.tar.lzma...
2021-05-09 13:35:22,073-0400 INFO  miktex-console.packagemanager - installing package l3backend
2021-05-09 13:35:22,074-0400 INFO  mainwindow - downloading https://ctan.math.illinois.edu/systems/win32/miktex/tm/packages/l3backend.tar.lzma...
2021-05-09 13:35:22,074-0400 INFO  miktex-console.packagemanager - going to download https://ctan.math.illinois.edu/systems/win32/miktex/tm/packages/l3backend.tar.lzma
2021-05-09 13:35:22,460-0400 INFO  mainwindow - 0.89 MB, 18.51 Mbit/s
2021-05-09 13:35:22,471-0400 INFO  mainwindow - visiting repository https://ctan.math.illinois.edu/systems/win32/miktex/tm/packages/...
2021-05-09 13:35:22,471-0400 INFO  mainwindow - repository type: remote package repository
2021-05-09 13:35:22,473-0400 INFO  mainwindow - loading package repository manifest...
2021-05-09 13:35:22,473-0400 INFO  mainwindow - downloading https://ctan.math.illinois.edu/systems/win32/miktex/tm/packages/miktex-zzdb1-2.9.tar.lzma...
2021-05-09 13:35:22,473-0400 INFO  miktex-console.packagemanager - going to download https://ctan.math.illinois.edu/systems/win32/miktex/tm/packages/miktex-zzdb1-2.9.tar.lzma
2021-05-09 13:35:22,614-0400 INFO  mainwindow - 0.21 MB, 11.87 Mbit/s
2021-05-09 13:35:22,756-0400 INFO  mainwindow - package repository digest: b2158409da406b706beff7147014b152
2021-05-09 13:35:22,758-0400 FATAL miktex-console.core - The operation could not be completed because a required file failed verification.
2021-05-09 13:35:22,758-0400 FATAL miktex-console.core - Data: package="l3backend", arhiveFile="C:\Users\johns\AppData\Local\Temp\mik261F.tmp", expectedMD5="47f7d88feead7c8108a86ad8ec5d0422", actualMD5="c42606db1554c2f3248bdd436447cdd6"
2021-05-09 13:35:22,759-0400 FATAL miktex-console.core - Source: Libraries\MiKTeX\PackageManager\PackageInstallerImpl.cpp:1257
2021-05-09 13:35:22,784-0400 ERROR mainwindow - Libraries\MiKTeX\PackageManager\PackageInstallerImpl.cpp:1257: The operation could not be completed because a required file failed verification.(package="l3backend", arhiveFile="C:\Users\johns\AppData\Local\Temp\mik261F.tmp", expectedMD5="47f7d88feead7c8108a86ad8ec5d0422", actualMD5="c42606db1554c2f3248bdd436447cdd6")
2021-05-09 13:35:40,814-0400 INFO  miktex-console.packagemanager - going to download https://api2.miktex.org/repositories?&releaseState=Stable
2021-05-09 13:35:49,638-0400 INFO  mainwindow - checking for updates...
2021-05-09 13:35:49,642-0400 INFO  miktex-console.packagemanager - searching for updateable packages
2021-05-09 13:35:49,644-0400 INFO  miktex-console.packagemanager - going to download https://api2.miktex.org/repositories/e499691f687378bd25ae27d08eee4497
2021-05-09 13:35:50,175-0400 INFO  mainwindow - downloading https://mirrors.rit.edu/CTAN/systems/win32/miktex/tm/packages/miktex-zzdb3-2.9.tar.lzma...
2021-05-09 13:35:50,175-0400 INFO  miktex-console.packagemanager - going to download https://mirrors.rit.edu/CTAN/systems/win32/miktex/tm/packages/miktex-zzdb3-2.9.tar.lzma
2021-05-09 13:35:50,891-0400 INFO  mainwindow - 1.19 MB, 13.28 Mbit/s
2021-05-09 13:35:51,880-0400 INFO  mainwindow - updating package manifests (C:\Users\johns\AppData\Local\Programs\MiKTeX\miktex/config\package-manifests.ini)...
2021-05-09 13:35:53,000-0400 INFO  mainwindow - installed 3935 package manifests
2021-05-09 13:35:53,000-0400 INFO  mainwindow - visiting repository https://mirrors.rit.edu/CTAN/systems/win32/miktex/tm/packages/...
2021-05-09 13:35:53,000-0400 INFO  mainwindow - repository type: remote package repository
2021-05-09 13:35:53,001-0400 INFO  mainwindow - loading package repository manifest...
2021-05-09 13:35:53,002-0400 INFO  mainwindow - downloading https://mirrors.rit.edu/CTAN/systems/win32/miktex/tm/packages/miktex-zzdb1-2.9.tar.lzma...
2021-05-09 13:35:53,002-0400 INFO  miktex-console.packagemanager - going to download https://mirrors.rit.edu/CTAN/systems/win32/miktex/tm/packages/miktex-zzdb1-2.9.tar.lzma
2021-05-09 13:35:53,183-0400 INFO  mainwindow - 0.21 MB, 9.24 Mbit/s
2021-05-09 13:35:54,115-0400 WARN  miktex-console.packagemanager - dependancy problem: tools is required by _miktex-latex-required
2021-05-09 13:35:54,115-0400 WARN  miktex-console.packagemanager - dependancy problem: miktex-doc-2.9 is required by _miktex-packages-2.9
2021-05-09 13:35:55,621-0400 INFO  mainwindow - package repository digest: b2158409da406b706beff7147014b152
2021-05-09 13:35:56,215-0400 INFO  mainwindow - found 102 updates
2021-05-09 13:35:56,227-0400 INFO  miktex-console.core - start process: pdftex --miktex-disable-installer --miktex-disable-maintenance --miktex-disable-diagnose --version
2021-05-09 13:35:58,373-0400 INFO  mainwindow - installing updates...
2021-05-09 13:35:58,374-0400 INFO  mainwindow - starting package maintenance...
2021-05-09 13:35:58,374-0400 INFO  mainwindow - installation directory: C:\Users\johns\AppData\Local\Programs\MiKTeX
2021-05-09 13:35:58,374-0400 INFO  mainwindow - package repository: https://mirrors.rit.edu/CTAN/systems/win32/miktex/tm/packages/
2021-05-09 13:35:58,502-0400 INFO  mainwindow - package repository digest: b2158409da406b706beff7147014b152
2021-05-09 13:35:58,503-0400 INFO  mainwindow - going to download 42956338 bytes
2021-05-09 13:35:58,503-0400 INFO  mainwindow - going to install 1746 file(s) (102 package(s))
2021-05-09 13:35:58,848-0400 INFO  miktex-console.packagemanager - installing package babel
2021-05-09 13:35:58,849-0400 INFO  mainwindow - downloading https://mirrors.rit.edu/CTAN/systems/win32/miktex/tm/packages/babel.tar.lzma...
2021-05-09 13:35:58,849-0400 INFO  miktex-console.packagemanager - going to download https://mirrors.rit.edu/CTAN/systems/win32/miktex/tm/packages/babel.tar.lzma
2021-05-09 13:35:59,149-0400 INFO  mainwindow - 1.69 MB, 45.28 Mbit/s
2021-05-09 13:35:59,410-0400 INFO  mainwindow - extracting files from babel.tar.lzma...
2021-05-09 13:36:00,240-0400 INFO  miktex-console.packagemanager - installing package csplain
2021-05-09 13:36:00,241-0400 INFO  mainwindow - downloading https://mirrors.rit.edu/CTAN/systems/win32/miktex/tm/packages/csplain.tar.lzma...
2021-05-09 13:36:00,241-0400 INFO  miktex-console.packagemanager - going to download https://mirrors.rit.edu/CTAN/systems/win32/miktex/tm/packages/csplain.tar.lzma
2021-05-09 13:36:00,484-0400 INFO  mainwindow - 1.72 MB, 56.91 Mbit/s
2021-05-09 13:36:00,528-0400 INFO  mainwindow - extracting files from csplain.tar.lzma...
2021-05-09 13:36:00,724-0400 INFO  miktex-console.packagemanager - installing package graphics-def
2021-05-09 13:36:00,724-0400 INFO  mainwindow - downloading https://mirrors.rit.edu/CTAN/systems/win32/miktex/tm/packages/graphics-def.tar.lzma...
2021-05-09 13:36:00,724-0400 INFO  miktex-console.packagemanager - going to download https://mirrors.rit.edu/CTAN/systems/win32/miktex/tm/packages/graphics-def.tar.lzma
2021-05-09 13:36:00,793-0400 INFO  mainwindow - 0.01 MB, 1.34 Mbit/s
2021-05-09 13:36:00,814-0400 INFO  mainwindow - extracting files from graphics-def.tar.lzma...
2021-05-09 13:36:00,835-0400 INFO  miktex-console.packagemanager - installing package hyperref
2021-05-09 13:36:00,835-0400 INFO  mainwindow - downloading https://mirrors.rit.edu/CTAN/systems/win32/miktex/tm/packages/hyperref.tar.lzma...
2021-05-09 13:36:00,835-0400 INFO  miktex-console.packagemanager - going to download https://mirrors.rit.edu/CTAN/systems/win32/miktex/tm/packages/hyperref.tar.lzma
2021-05-09 13:36:01,242-0400 INFO  mainwindow - 3.82 MB, 75.18 Mbit/s
2021-05-09 13:36:01,281-0400 INFO  mainwindow - extracting files from hyperref.tar.lzma...
2021-05-09 13:36:01,527-0400 INFO  miktex-console.packagemanager - installing package hyph-utf8
2021-05-09 13:36:01,528-0400 INFO  mainwindow - downloading https://mirrors.rit.edu/CTAN/systems/win32/miktex/tm/packages/hyph-utf8.tar.lzma...
2021-05-09 13:36:01,528-0400 INFO  miktex-console.packagemanager - going to download https://mirrors.rit.edu/CTAN/systems/win32/miktex/tm/packages/hyph-utf8.tar.lzma
2021-05-09 13:36:01,724-0400 INFO  mainwindow - 1.88 MB, 76.20 Mbit/s
2021-05-09 13:36:01,876-0400 INFO  mainwindow - extracting files from hyph-utf8.tar.lzma...
2021-05-09 13:36:02,477-0400 INFO  miktex-console.packagemanager - installing package l3backend
2021-05-09 13:36:02,478-0400 INFO  mainwindow - downloading https://mirrors.rit.edu/CTAN/systems/win32/miktex/tm/packages/l3backend.tar.lzma...
2021-05-09 13:36:02,478-0400 INFO  miktex-console.packagemanager - going to download https://mirrors.rit.edu/CTAN/systems/win32/miktex/tm/packages/l3backend.tar.lzma
2021-05-09 13:36:02,629-0400 INFO  mainwindow - 0.89 MB, 47.51 Mbit/s
2021-05-09 13:36:02,639-0400 INFO  mainwindow - visiting repository https://mirrors.rit.edu/CTAN/systems/win32/miktex/tm/packages/...
2021-05-09 13:36:02,639-0400 INFO  mainwindow - repository type: remote package repository
2021-05-09 13:36:02,641-0400 INFO  mainwindow - loading package repository manifest...
2021-05-09 13:36:02,641-0400 INFO  mainwindow - downloading https://mirrors.rit.edu/CTAN/systems/win32/miktex/tm/packages/miktex-zzdb1-2.9.tar.lzma...
2021-05-09 13:36:02,641-0400 INFO  miktex-console.packagemanager - going to download https://mirrors.rit.edu/CTAN/systems/win32/miktex/tm/packages/miktex-zzdb1-2.9.tar.lzma
2021-05-09 13:36:02,710-0400 INFO  mainwindow - 0.21 MB, 24.25 Mbit/s
2021-05-09 13:36:02,853-0400 INFO  mainwindow - package repository digest: b2158409da406b706beff7147014b152
2021-05-09 13:36:02,855-0400 FATAL miktex-console.core - The operation could not be completed because a required file failed verification.
2021-05-09 13:36:02,855-0400 FATAL miktex-console.core - Data: package="l3backend", arhiveFile="C:\Users\johns\AppData\Local\Temp\mikC3F0.tmp", expectedMD5="47f7d88feead7c8108a86ad8ec5d0422", actualMD5="c42606db1554c2f3248bdd436447cdd6"
2021-05-09 13:36:02,855-0400 FATAL miktex-console.core - Source: Libraries\MiKTeX\PackageManager\PackageInstallerImpl.cpp:1257
2021-05-09 13:36:02,878-0400 ERROR mainwindow - Libraries\MiKTeX\PackageManager\PackageInstallerImpl.cpp:1257: The operation could not be completed because a required file failed verification.(package="l3backend", arhiveFile="C:\Users\johns\AppData\Local\Temp\mikC3F0.tmp", expectedMD5="47f7d88feead7c8108a86ad8ec5d0422", actualMD5="c42606db1554c2f3248bdd436447cdd6")
2021-05-09 13:38:01,120-0400 INFO  mainwindow - checking for updates...
2021-05-09 13:38:01,125-0400 INFO  miktex-console.packagemanager - searching for updateable packages
2021-05-09 13:38:01,128-0400 INFO  mainwindow - downloading https://mirrors.rit.edu/CTAN/systems/win32/miktex/tm/packages/miktex-zzdb3-2.9.tar.lzma...
2021-05-09 13:38:01,128-0400 INFO  miktex-console.packagemanager - going to download https://mirrors.rit.edu/CTAN/systems/win32/miktex/tm/packages/miktex-zzdb3-2.9.tar.lzma
2021-05-09 13:38:01,759-0400 INFO  mainwindow - 1.19 MB, 15.05 Mbit/s
2021-05-09 13:38:02,783-0400 INFO  mainwindow - updating package manifests (C:\Users\johns\AppData\Local\Programs\MiKTeX\miktex/config\package-manifests.ini)...
2021-05-09 13:38:03,926-0400 INFO  mainwindow - installed 3935 package manifests
2021-05-09 13:38:03,926-0400 INFO  mainwindow - visiting repository https://mirrors.rit.edu/CTAN/systems/win32/miktex/tm/packages/...
2021-05-09 13:38:03,926-0400 INFO  mainwindow - repository type: remote package repository
2021-05-09 13:38:03,928-0400 INFO  mainwindow - loading package repository manifest...
2021-05-09 13:38:03,928-0400 INFO  mainwindow - downloading https://mirrors.rit.edu/CTAN/systems/win32/miktex/tm/packages/miktex-zzdb1-2.9.tar.lzma...
2021-05-09 13:38:03,928-0400 INFO  miktex-console.packagemanager - going to download https://mirrors.rit.edu/CTAN/systems/win32/miktex/tm/packages/miktex-zzdb1-2.9.tar.lzma
2021-05-09 13:38:04,106-0400 INFO  mainwindow - 0.21 MB, 9.40 Mbit/s
2021-05-09 13:38:05,055-0400 WARN  miktex-console.packagemanager - dependancy problem: tools is required by _miktex-latex-required
2021-05-09 13:38:05,055-0400 WARN  miktex-console.packagemanager - dependancy problem: miktex-doc-2.9 is required by _miktex-packages-2.9
2021-05-09 13:38:06,591-0400 INFO  mainwindow - package repository digest: b2158409da406b706beff7147014b152
2021-05-09 13:38:07,175-0400 INFO  mainwindow - found 102 updates
2021-05-09 13:38:07,186-0400 INFO  miktex-console.core - start process: pdftex --miktex-disable-installer --miktex-disable-maintenance --miktex-disable-diagnose --version
2021-05-09 13:38:17,496-0400 INFO  mainwindow - installing updates...
2021-05-09 13:38:17,497-0400 INFO  mainwindow - starting package maintenance...
2021-05-09 13:38:17,497-0400 INFO  mainwindow - installation directory: C:\Users\johns\AppData\Local\Programs\MiKTeX
2021-05-09 13:38:17,497-0400 INFO  mainwindow - package repository: https://mirrors.rit.edu/CTAN/systems/win32/miktex/tm/packages/
2021-05-09 13:38:17,617-0400 INFO  mainwindow - package repository digest: b2158409da406b706beff7147014b152
2021-05-09 13:38:17,617-0400 INFO  mainwindow - going to download 42956338 bytes
2021-05-09 13:38:17,617-0400 INFO  mainwindow - going to install 1746 file(s) (102 package(s))
2021-05-09 13:38:17,966-0400 INFO  miktex-console.packagemanager - installing package babel
2021-05-09 13:38:17,967-0400 INFO  mainwindow - downloading https://mirrors.rit.edu/CTAN/systems/win32/miktex/tm/packages/babel.tar.lzma...
2021-05-09 13:38:17,967-0400 INFO  miktex-console.packagemanager - going to download https://mirrors.rit.edu/CTAN/systems/win32/miktex/tm/packages/babel.tar.lzma
2021-05-09 13:38:18,242-0400 INFO  mainwindow - 1.69 MB, 49.23 Mbit/s
2021-05-09 13:38:18,507-0400 INFO  mainwindow - extracting files from babel.tar.lzma...
2021-05-09 13:38:19,447-0400 INFO  miktex-console.packagemanager - installing package csplain
2021-05-09 13:38:19,448-0400 INFO  mainwindow - downloading https://mirrors.rit.edu/CTAN/systems/win32/miktex/tm/packages/csplain.tar.lzma...
2021-05-09 13:38:19,448-0400 INFO  miktex-console.packagemanager - going to download https://mirrors.rit.edu/CTAN/systems/win32/miktex/tm/packages/csplain.tar.lzma
2021-05-09 13:38:19,690-0400 INFO  mainwindow - 1.72 MB, 56.91 Mbit/s
2021-05-09 13:38:19,736-0400 INFO  mainwindow - extracting files from csplain.tar.lzma...
2021-05-09 13:38:19,930-0400 INFO  miktex-console.packagemanager - installing package graphics-def
2021-05-09 13:38:19,930-0400 INFO  mainwindow - downloading https://mirrors.rit.edu/CTAN/systems/win32/miktex/tm/packages/graphics-def.tar.lzma...
2021-05-09 13:38:19,930-0400 INFO  miktex-console.packagemanager - going to download https://mirrors.rit.edu/CTAN/systems/win32/miktex/tm/packages/graphics-def.tar.lzma
2021-05-09 13:38:20,031-0400 INFO  mainwindow - 0.01 MB, 0.91 Mbit/s
2021-05-09 13:38:20,045-0400 INFO  mainwindow - extracting files from graphics-def.tar.lzma...
2021-05-09 13:38:20,064-0400 INFO  miktex-console.packagemanager - installing package hyperref
2021-05-09 13:38:20,065-0400 INFO  mainwindow - downloading https://mirrors.rit.edu/CTAN/systems/win32/miktex/tm/packages/hyperref.tar.lzma...
2021-05-09 13:38:20,065-0400 INFO  miktex-console.packagemanager - going to download https://mirrors.rit.edu/CTAN/systems/win32/miktex/tm/packages/hyperref.tar.lzma
2021-05-09 13:38:20,464-0400 INFO  mainwindow - 3.82 MB, 76.69 Mbit/s
2021-05-09 13:38:20,497-0400 INFO  mainwindow - extracting files from hyperref.tar.lzma...
2021-05-09 13:38:20,761-0400 INFO  miktex-console.packagemanager - installing package hyph-utf8
2021-05-09 13:38:20,761-0400 INFO  mainwindow - downloading https://mirrors.rit.edu/CTAN/systems/win32/miktex/tm/packages/hyph-utf8.tar.lzma...
2021-05-09 13:38:20,761-0400 INFO  miktex-console.packagemanager - going to download https://mirrors.rit.edu/CTAN/systems/win32/miktex/tm/packages/hyph-utf8.tar.lzma
2021-05-09 13:38:20,962-0400 INFO  mainwindow - 1.88 MB, 75.05 Mbit/s
2021-05-09 13:38:21,112-0400 INFO  mainwindow - extracting files from hyph-utf8.tar.lzma...
2021-05-09 13:38:21,714-0400 INFO  miktex-console.packagemanager - installing package l3backend
2021-05-09 13:38:21,715-0400 INFO  mainwindow - downloading https://mirrors.rit.edu/CTAN/systems/win32/miktex/tm/packages/l3backend.tar.lzma...
2021-05-09 13:38:21,715-0400 INFO  miktex-console.packagemanager - going to download https://mirrors.rit.edu/CTAN/systems/win32/miktex/tm/packages/l3backend.tar.lzma
2021-05-09 13:38:21,836-0400 INFO  mainwindow - 0.89 MB, 58.89 Mbit/s
2021-05-09 13:38:21,846-0400 INFO  mainwindow - visiting repository https://mirrors.rit.edu/CTAN/systems/win32/miktex/tm/packages/...
2021-05-09 13:38:21,846-0400 INFO  mainwindow - repository type: remote package repository
2021-05-09 13:38:21,848-0400 INFO  mainwindow - loading package repository manifest...
2021-05-09 13:38:21,848-0400 INFO  mainwindow - downloading https://mirrors.rit.edu/CTAN/systems/win32/miktex/tm/packages/miktex-zzdb1-2.9.tar.lzma...
2021-05-09 13:38:21,848-0400 INFO  miktex-console.packagemanager - going to download https://mirrors.rit.edu/CTAN/systems/win32/miktex/tm/packages/miktex-zzdb1-2.9.tar.lzma
2021-05-09 13:38:21,921-0400 INFO  mainwindow - 0.21 MB, 23.24 Mbit/s
2021-05-09 13:38:22,072-0400 INFO  mainwindow - package repository digest: b2158409da406b706beff7147014b152
2021-05-09 13:38:22,074-0400 FATAL miktex-console.core - The operation could not be completed because a required file failed verification.
2021-05-09 13:38:22,075-0400 FATAL miktex-console.core - Data: package="l3backend", arhiveFile="C:\Users\johns\AppData\Local\Temp\mikE3EC.tmp", expectedMD5="47f7d88feead7c8108a86ad8ec5d0422", actualMD5="c42606db1554c2f3248bdd436447cdd6"
2021-05-09 13:38:22,075-0400 FATAL miktex-console.core - Source: Libraries\MiKTeX\PackageManager\PackageInstallerImpl.cpp:1257
2021-05-09 13:38:22,096-0400 ERROR mainwindow - Libraries\MiKTeX\PackageManager\PackageInstallerImpl.cpp:1257: The operation could not be completed because a required file failed verification.(package="l3backend", arhiveFile="C:\Users\johns\AppData\Local\Temp\mikE3EC.tmp", expectedMD5="47f7d88feead7c8108a86ad8ec5d0422", actualMD5="c42606db1554c2f3248bdd436447cdd6")

I've tried multiple (five) different mirrors to no avail when updating, each fail on the same step. 

- [ x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

**Comment by edocevoli** [comment] 2021-05-09 19:31
Duplicate of #809

**Closed by edocevoli** 2021-05-09 19:31 UTC
