### ISSUE TITLE
ERROR HELPS IN THE MIKTEX DEBIAN 9 INSTALLATION PROCESS

### ISSUE THREAD

**Issue by Dmiranda0** [MiKTeX/miktex#610] opened 2020-09-02 15:23 UTC
Hello, good morning, recently I placed a Debian 9 case and it was marked as solved and the problem is not solved, the fact is that when I followed the installation steps of its official page, it gave me the error “Cannot find the miktex package ”And I do not know how to solve it attached image.

![Error Miktex Debian 9](https://user-images.githubusercontent.com/70546278/92003198-5af7d700-ed06-11ea-92b3-ea9f859e554b.PNG)

I kindly request your support for a quick solution.
Regards.

**Comment by edocevoli** [comment] 2020-09-02 15:35
Duplicate of #608

**Comment by edocevoli** [comment] 2020-09-02 15:38
Please state exactly what you did so that we can see what went wrong. Please do not attach screenshots. Instead, copy the transcript of your terminal window and paste it into your next comment.

**Comment by Dmiranda0** [comment] 2020-09-02 16:22
The steps indicated in the Miktex page were carried out for the installation and when executing the commands it sent me the following in the terminal window:

**root @ debian: / home / risklogic # sudo apt-get install miktex
Reading package list ... Done
Creating dependency tree
Reading the status information ... Done
E: The miktex package could not be located
root @ debian: / home / risklogic #**

This was what was executed according to what was indicated from the page:
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys D6BC243565B2087BC3F897C9277A7293F59E4889
echo "deb http://miktex.org/download/debian stretch universe" | sudo tee /etc/apt/sources.list.d/miktex.list
sudo apt-get update
sudo apt-get install miktex

**Comment by edocevoli** [comment] 2020-09-02 16:26
Thanks. Is this a 64-bit system?

**Comment by Dmiranda0** [comment] 2020-09-02 16:29
It is correct it is 64 bit, it is in a virtual machine

![image](https://user-images.githubusercontent.com/70546278/92010528-83380380-ed0f-11ea-9f19-6ca4905688d5.png)

**Comment by edocevoli** [comment] 2020-09-02 16:40
Your first screenshot shows some warnings. They should give you some hints about how to proceed. There seems to be a conflict between `miktex` and other packages installed on your system.

**Comment by edocevoli** [comment] 2020-09-02 16:41
At the moment I am not able to reproduce this system-dependent issue. A solution/fix cannot be provided.

**Closed by edocevoli** 2020-09-02 16:41 UTC
