### ISSUE TITLE
Can not Build and View pdfLatex for the first time in windows

### ISSUE THREAD

**Issue by xzghx** [MiKTeX/miktex#721] opened 2021-02-20 12:55 UTC
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

I've  installed MikTex and then TexStudio but I can not compile a simple code like `\documentclass{article}` with miktex and gives error  :
```
Could not start Build & View PdfLatex:
pdflatex.exe -synctex=1 -interaction=nonstopmode "test1".tex.
```
Before opennig issue here I searched a lot and tried solutions I checked configurations and couldn't run it .

- MiKTeX installation report
```
ReportDate: 2021-02-20 16:16:31
CurrentVersion: 21.1
SetupDate: 2021-02-14 12:18:00
SetupVersion: 21.1
Configuration: Regular
GitInfo: 9ac490e / 2021-01-25 20:14:00
OS: Windows 10 Pro, 64-bit, build 10240
SharedSetup: no
LinkTargetDirectory: C:\Users\z.gh\AppData\Local\Programs\MiKTeX\miktex\bin\x64
PathOkay: yes
LastUpdateCheck: 2021-02-20 16:13:00
LastUpdate: 2021-02-20 16:13:58
LastUpdateDb: 2021-02-20 16:12:59
SystemAdmin: yes
RootPrivileges: no
AdminMode: no
Root0: C:\Users\z.gh\AppData\Roaming\MiKTeX
Root1: C:\Users\z.gh\AppData\Local\MiKTeX
Root2: C:\Users\z.gh\AppData\Local\Programs\MiKTeX
Root3: C:\ProgramData\MiKTeX
Root4: C:\Program Files\MiKTeX
UserInstall: C:\Users\z.gh\AppData\Local\Programs\MiKTeX
UserConfig: C:\Users\z.gh\AppData\Roaming\MiKTeX
UserData: C:\Users\z.gh\AppData\Local\MiKTeX
CommonInstall: C:\Program Files\MiKTeX
CommonConfig: C:\ProgramData\MiKTeX
CommonData: C:\ProgramData\MiKTeX
```

- pdfLatex.log
 ```
2021-02-20 16:19:31,963+0330 INFO  pdflatex - this process (11980) started by 'texstudio' with command line: pdflatex.exe -synctex=1 -interaction=nonstopmode test1.tex
2021-02-20 16:19:31,972+0330 INFO  pdflatex - allowing known shell commands
2021-02-20 16:19:32,009+0330 INFO  pdflatex - going to create file: pdflatex.fmt
2021-02-20 16:19:32,043+0330 INFO  pdflatex.core - start process: initexmf --dump-by-name=pdflatex --engine=pdftex
2021-02-20 16:19:33,358+0330 ERROR pdflatex - C:\Users\z.gh\AppData\Local\Programs\MiKTeX\miktex\bin\x64\initexmf.exe did not succeed; exitCode: 1
2021-02-20 16:19:33,358+0330 ERROR pdflatex - output:
2021-02-20 16:19:33,358+0330 ERROR pdflatex - 
Sorry, but "MiKTeX Configuration Utility" did not succeed.

The log file hopefully contains the information to get MiKTeX going again:

  C:\Users\z.gh\AppData\Local\MiKTeX\miktex\log\initexmf.log

2021-02-20 16:19:33,358+0330 FATAL pdflatex.core - The memory dump file could not be found.
2021-02-20 16:19:33,358+0330 FATAL pdflatex.core - Data: fileName="pdflatex.fmt"
2021-02-20 16:19:33,358+0330 FATAL pdflatex.core - Source: Libraries\MiKTeX\TeXAndFriends\texmfapp.cpp:717
2021-02-20 16:19:33,358+0330 FATAL pdflatex - The memory dump file could not be found.
2021-02-20 16:19:33,358+0330 FATAL pdflatex - Info: fileName="pdflatex.fmt"
2021-02-20 16:19:33,358+0330 FATAL pdflatex - Source: Libraries\MiKTeX\TeXAndFriends\texmfapp.cpp
2021-02-20 16:19:33,358+0330 FATAL pdflatex - Line: 717
2021-02-20 16:19:33,358+0330 INFO  pdflatex - this process (11980) finishes with exit code 1

```

- initexmf.log
```
2021-02-20 16:20:48,433+0330 INFO  initexmf - this is MiKTeX Configuration Utility 4.2 (MiKTeX 21.1)
2021-02-20 16:20:48,433+0330 INFO  initexmf - this process (12240) started by 'latex' with command line: initexmf --dump-by-name=pdflatex --engine=pdftex
2021-02-20 16:20:48,433+0330 INFO  initexmf - Operating on the private (per-user) MiKTeX setup
2021-02-20 16:20:48,439+0330 INFO  initexmf - running: miktex-makefmt.exe --engine=pdftex --dest-name=pdflatex --no-dump pdflatex.ini --engine-option=-tcx=cp227.tcx --miktex-disable-maintenance --miktex-disable-diagnose
2021-02-20 16:20:48,474+0330 INFO  initexmf.core - start process: miktex-makefmt.exe --engine=pdftex --dest-name=pdflatex --no-dump pdflatex.ini --engine-option=-tcx=cp227.tcx --miktex-disable-maintenance --miktex-disable-diagnose
2021-02-20 16:20:49,298+0330 ERROR initexmf - sub-process error output has been saved to 'C:\Users\z.gh\AppData\Local\MiKTeX\miktex\log\miktex-makefmt_2021-02-20-162049.out'
2021-02-20 16:20:49,298+0330 FATAL initexmf - The executed process did not succeed.
2021-02-20 16:20:49,298+0330 FATAL initexmf - Info: fileName="C:\Users\z.gh\AppData\Local\Programs\MiKTeX\miktex\bin\x64\miktex-makefmt.exe", exitCode="1"
2021-02-20 16:20:49,298+0330 FATAL initexmf - Source: 
2021-02-20 16:20:49,298+0330 FATAL initexmf - Line: 0
2021-02-20 16:20:49,298+0330 INFO  initexmf - this process (12240) finishes with exit code 1

```

**Comment by edocevoli** [comment] 2021-02-20 15:58
See #662

**Comment by edocevoli** [comment] 2021-02-20 15:58
Duplicate of #662

**Closed by edocevoli** 2021-02-20 15:58 UTC
