### ISSUE TITLE
MikTex for Windows virus found

### ISSUE THREAD

**Issue by mseress** [MiKTeX/miktex#426] opened 2019-12-01 15:19 UTC
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

When I download basic-miktex-2.9.7269-x64.exe for Windows10 from the miktech.org website, Windows Defender immediatelly notifies me that it's a virus, and deletes it right away. I couldn't even calculate the checksum, because PowerShell gives this error:

**get-filehash : The file 'basic-miktex-2.9.7269-x64.exe' cannot be read: Operation did not
complete successfully because the file contains a virus or potentially unwanted software.**

Repeated twice, with same results.

Can you please solve it?

**Comment by edocevoli** [comment] 2019-12-01 15:29
Duplicate of #421

**Closed by edocevoli** 2019-12-01 15:29 UTC
