### ISSUE TITLE
Found a Trojaner (win32/azden.A!cl) 

### ISSUE THREAD

**Issue by HISKrawczyk** [MiKTeX/miktex#425] opened 2019-11-29 14:10 UTC
My buisness virus scanner found a trojaner in the installer https://miktex.org/download/ctan/systems/win32/miktex/setup/windows-x64/basic-miktex-2.9.7269-x64.exe 

i hope i can little bit help. Best Regards Patrick :) 

- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

**Comment by finlaybob** [comment] 2019-11-29 14:14
Seen this too with the latest download 
![image](https://user-images.githubusercontent.com/2033345/69874331-99152580-12b2-11ea-9147-f07cd3cea5ef.png)

**Comment by ivankokan** [comment] 2019-11-29 14:21
A duplicate of #421. Can you specify the antiviruses you use?

**Comment by HISKrawczyk** [comment] 2019-11-29 14:24
Oh sorry, i dont see #421. We use windows defender / endpoint protection as antiviruses.

**Comment by ivankokan** [comment] 2019-11-29 14:26
Report it as false positive: https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/developer-resources.

**Comment by edocevoli** [comment] 2019-11-29 16:07
Duplicate of #421

**Closed** 2019-11-29 16:08 UTC
Labels: duplicate
