### ISSUE TITLE
latest update breaks yap...

### ISSUE THREAD

**Issue by cooch17** [MiKTeX/miktex#506] opened 2020-04-20 00:15 UTC
Latest update breaks yap. When I try compiling even simply files, and then try to open the .dvi with yap, I get an error about 'no conversion from undefined configuration value to boolean'. See below. 

MiKTeX Problem Report
Message: Configuration error: no conversion from undefined configuration value to boolean.
Data: 
Source: Libraries\MiKTeX\Core\Session\config.cpp
Line: 641
MiKTeX: 2.9.7400
OS: Windows 10 Home, 64-bit, build 18363
Invokers: non-existing/explorer/WinEdt
SystemAdmin: no
Root0: C:\Users\egc\AppData\Roaming\MiKTeX\2.9
Root1: C:\Users\egc\AppData\Local\MiKTeX\2.9
Root2: C:\Users\egc\Desktop\egc\text\MikTeX
Root3: C:\ProgramData\MiKTeX\2.9
Root4: C:\Program Files\MiKTeX 2.9
UserInstall: C:\Users\egc\Desktop\egc\text\MikTeX
UserConfig: C:\Users\egc\AppData\Roaming\MiKTeX\2.9
UserData: C:\Users\egc\AppData\Local\MiKTeX\2.9
CommonInstall: C:\Program Files\MiKTeX 2.9
CommonConfig: C:\ProgramData\MiKTeX\2.9
CommonData: C:\ProgramData\MiKTeX\2.9

**Comment by edocevoli** [comment] 2020-04-20 08:02
I cannot reproduce the issue with the today's update. If you still cannot open a DVI file: please create a Zip archive containing the log files.

**Comment by cooch17** [comment] 2020-04-20 13:47
Just tried the update again, 5 minutes ago.  Presumably, latest build.  Exact same error.

MiKTeX Problem Report
**Message:** Configuration error: no conversion from undefined configuration value to boolean.**
Data: 
Source: Libraries\MiKTeX\Core\Session\config.cpp
Line: 641
MiKTeX: 2.9.7400
OS: Windows 10 Pro, 64-bit, build 18363
Invokers: non-existing/explorer/WinEdt
SystemAdmin: no
Root0: C:\Users\egc\AppData\Roaming\MiKTeX\2.9
Root1: C:\Users\egc\AppData\Local\MiKTeX\2.9
Root2: C:\Users\egc\Desktop\egc\text\MikTeX
Root3: C:\ProgramData\MiKTeX\2.9
Root4: C:\Program Files\MiKTeX 2.9
UserInstall: C:\Users\egc\Desktop\egc\text\MikTeX
UserConfig: C:\Users\egc\AppData\Roaming\MiKTeX\2.9
UserData: C:\Users\egc\AppData\Local\MiKTeX\2.9
CommonInstall: C:\Program Files\MiKTeX 2.9
CommonConfig: C:\ProgramData\MiKTeX\2.9
CommonData: C:\ProgramData\MiKTeX\2.9

When you ask for 'log files' - logs from what?

**Comment by edocevoli** [comment] 2020-04-20 14:10
MiKTeX log files in `C:\Users\egc\AppData\Local\MiKTeX\2.9\miktex\log`

**Comment by edocevoli** [comment] 2020-04-20 14:30
This is what I have done:

```
latex sample2e
yap sample2e.dvi
```

Works for me.

**Comment by cooch17** [comment] 2020-04-20 14:42
Not for me - using either my own simple MWE (attached), or what you try (above). Logs attached.

If it matters, Win 10 Pro, 64-bit MikTeX. 
[log.zip](https://github.com/MiKTeX/miktex/files/4504183/log.zip)
[simple_mwe.zip](https://github.com/MiKTeX/miktex/files/4504187/simple_mwe.zip)

**Comment by edocevoli** [comment] 2020-04-20 15:06
Thank you. There is no Yap log file and that reminds me that Yap logging is not enabled. I will enable logging (later this week) and then we might get more information.

**Comment by cooch17** [comment] 2020-04-20 15:11
Perfect -- thanks. In the meantime, I'll roll back to my previous install, which works perfectly.

**Comment by cooch17** [comment] 2020-04-20 16:55
Just to rule out 'system issues', I did a fresh install of Windows 10 (Pro,  but that doesn't matter) in a virtual machine on my of my Linux boxes. Downloaded the latest MikTeX 64-bit installer, installed for 'me only' (I install into a directory on my Desktop), applied the slew of updates, and tried

     `latex sample2e'
     `yap sample2e.dvi'

No change. Still get the same 'no conversion from undefined configuration value to boolean' error.

**Comment by paultjevdh** [comment] 2020-04-21 07:38
Hi, I have exactly the same issue. You're not alone.
Paul

**Comment by cooch17** [comment] 2020-04-21 12:09
Thanks  - always 'comforting' (if thats the right word) to know the problem is a least somewhat more 'general' than simply 'my machines'.

**Comment by paultjevdh** [comment] 2020-04-22 06:54
Yesterdays update fixes it for me.
Paul

**Comment by paultjevdh** [comment] 2020-04-22 07:33
...but I think that forward search is now broken :-(
Paul

**Comment by edocevoli** [comment] 2020-04-22 08:39
@paultjevdh: in order to diagnose the new issue: Yap logging is now enabled. You can see a live trace via [DebugView](https://docs.microsoft.com/en-us/sysinternals/downloads/debugview).

**Comment by edocevoli** [comment] 2020-04-22 09:22
@paultjevdh  thank you for reporting it; this will be fixed with the next update.

**Comment by cooch17** [comment] 2020-04-22 13:09
Confirmed -- forward search not functioning, whereas reverse search works as it should. 

But thanks for getting basic yap functionality back! One step forward...

**Comment by paultjevdh** [comment] 2020-04-23 07:00
Hi,
In the Wednesday release, forward search seems to work again. Thanks very much.
Bye,
Paul

**Closed** 2020-04-23 09:54 UTC
