### ISSUE TITLE
WIN64: '! Missing number, treated as zero ... ! Missing } inserted' error for GMP documentation builds

### ISSUE THREAD

**Issue by sav-ix** [MiKTeX/miktex#103] opened 2018-04-01 13:15 UTC
Hello, everyone,

For GMP `.pdf` documentation builds using MiKTeX got error:
```
make install-pdf

<snip>

Making install-pdf in doc
make[1]: Entering directory '/c/libGMP-6.1.99-dev/build/doc'
TEXINPUTS=".:$TEXINPUTS" \
MAKEINFO='/bin/sh /c/libGMP-6.1.99-dev/build/missing makeinfo   -I .' \
texi2dvi --pdf --batch  --build-dir=gmp.t2p -o gmp.pdf  \
gmp.texi
This is pdfTeX, Version 3.14159265-2.6-1.40.19 (MiKTeX 2.9.6630 64-bit)
entering extended mode

(../../../.././gmp.texi
(C:\libGMP-6.1.99-dev\build\doc\texinfo.tex
Loading texinfo [version 2017-06-04.19]: pdf, fonts, markup, glyphs,
page headings, tables, conditionals, indexing, sectioning, toc, environments,
defuns, macros, cross references, insertions,
("C:\Program Files\PrgDev\MiKTeX\texmfs\install\tex\generic\epsf\epsf.tex"
This is `epsf.tex' v2.7.4 <14 February 2011>
) localization, formatting, and turning on texinfo input format.)
(C:\libGMP-6.1.99-dev\build\doc\version.texi)
Writing index file gmp.fn
[1{C:/Program Files/PrgDev/MiKTeX/texmfs/data/pdftex/config/pdftex.map}]
Cross reference values unknown; you must run TeX again. [2] [-1] [-2]
(GNU MP Copying Conditions)
Writing index file gmp.cp
Chapter 1 [1] Chapter 2 [2] [3] [4]
Underfull \hbox (badness 10000) in paragraph at lines 826--838
 []@textrm SPARC: `@texttt sparc[]@textrm '[], `@texttt sparcv8[]@textrm '[], `
@texttt microsparc[]@textrm '[], `@texttt supersparc[]@textrm '[], `@texttt spa
rcv9[]@textrm '[],
[5] [6] [7] [8] [9] [10] [11] [12] [13] [14] [15] Chapter 3 [16] [17] [18]
[19]
Underfull \hbox (badness 7168) in paragraph at lines 2169--2173
 []@textrm If con-fig-ured with @texttt --enable-alloca=malloc-notreentrant[] @
textrm (or with @texttt --enable-
[20]
Writing index file gmp.vr
[21]
Underfull \hbox (badness 7576) in paragraph at lines 2370--2377
 [][][][]@textrm The `@texttt perl[]@textrm '[] sub-di-rec-tory is a com-pre-he
n-sive perl in-ter-face to GMP. See
[22] [23] [24] [25] [26] [27] Chapter 4 [28] Chapter 5 [29] [30] [31] [32]
[33] [34] [35] [36] [37] [38] [39] [40] [41] [42] [43] [44] [45] Chapter 6
[46] [47] [48] [49] Chapter 7 [50] [51] [52] [53] [54] [55] [56] [57]
Chapter 8 [58] [59] [60] [61] [62] [63] [64] [65] [66] [67] [68] [69]
Chapter 9 [70] [71] Chapter 10 [72] [73] [74] [75] [76] Chapter 11 [77]
[78] [79] [80] Chapter 12 [81] [82] [83] [84] [85] [86] [87] [88] [89]
Chapter 13 [90] [91] Chapter 14 [92] [93] Chapter 15 [94]
Underfull \hbox (badness 10000) detected at line 7763
|
[95] [96] [97] [98] [99] [100] [101] [102] [103] [104] [105] [106] [107]
[108] [109] [110] [111] [112] [113] [114] [115] [116] [117] [118] Chapter 16
[119] [120] [121] [122] [123] Appendix A [124] [125] Appendix B [126] [127]
Appendix C [128]
(C:\libGMP-6.1.99-dev\build\doc\fdl-1.3.texi [129]
[130] [131] [132] [133] [134]) (Concept Index) [135]
No file gmp.cps.
(Function and Type Index) [136]
No file gmp.fns.
[137] )
(see the transcript file for additional information)pdfTeX warning (\pdffontatt
r): fonts @textsl and @defsl have conflicting attributes; I will ignore the att
ributes assigned to @textsl

<C:/Program Files/PrgDev/MiKTeX/texmfs/install/fonts/type1/public/amsfonts/cm/c
mb10.pfb><C:/Program Files/PrgDev/MiKTeX/texmfs/install/fonts/type1/public/amsf
onts/cm/cmbx12.pfb><C:/Program Files/PrgDev/MiKTeX/texmfs/install/fonts/type1/p
ublic/amsfonts/cm/cmcsc10.pfb><C:/Program Files/PrgDev/MiKTeX/texmfs/install/fo
nts/type1/public/amsfonts/cm/cmex10.pfb><C:/Program Files/PrgDev/MiKTeX/texmfs/
install/fonts/type1/public/amsfonts/cm/cmmi10.pfb><C:/Program Files/PrgDev/MiKT
eX/texmfs/install/fonts/type1/public/amsfonts/cm/cmmi5.pfb><C:/Program Files/Pr
gDev/MiKTeX/texmfs/install/fonts/type1/public/amsfonts/cm/cmmi7.pfb><C:/Program
 Files/PrgDev/MiKTeX/texmfs/install/fonts/type1/public/amsfonts/cm/cmr10.pfb><C
:/Program Files/PrgDev/MiKTeX/texmfs/install/fonts/type1/public/amsfonts/cm/cmr
5.pfb><C:/Program Files/PrgDev/MiKTeX/texmfs/install/fonts/type1/public/amsfont
s/cm/cmr7.pfb><C:/Program Files/PrgDev/MiKTeX/texmfs/install/fonts/type1/public
/amsfonts/cm/cmr9.pfb><C:/Program Files/PrgDev/MiKTeX/texmfs/install/fonts/type
1/public/amsfonts/cm/cmsl10.pfb><C:/Program Files/PrgDev/MiKTeX/texmfs/install/
fonts/type1/public/amsfonts/cm/cmsltt10.pfb><C:/Program Files/PrgDev/MiKTeX/tex
mfs/install/fonts/type1/public/amsfonts/cm/cmss10.pfb><C:/Program Files/PrgDev/
MiKTeX/texmfs/install/fonts/type1/public/amsfonts/cm/cmsy10.pfb><C:/Program Fil
es/PrgDev/MiKTeX/texmfs/install/fonts/type1/public/amsfonts/cm/cmsy5.pfb><C:/Pr
ogram Files/PrgDev/MiKTeX/texmfs/install/fonts/type1/public/amsfonts/cm/cmsy7.p
fb><C:/Program Files/PrgDev/MiKTeX/texmfs/install/fonts/type1/public/amsfonts/c
m/cmti10.pfb><C:/Program Files/PrgDev/MiKTeX/texmfs/install/fonts/type1/public/
amsfonts/cm/cmtt10.pfb><C:/Program Files/PrgDev/MiKTeX/texmfs/install/fonts/typ
e1/public/amsfonts/cm/cmtt12.pfb><C:/Program Files/PrgDev/MiKTeX/texmfs/install
/fonts/type1/public/amsfonts/cm/cmtt9.pfb>
Output written on gmp.pdf (141 pages, 842595 bytes).
Transcript written on gmp.log.
This is pdfTeX, Version 3.14159265-2.6-1.40.19 (MiKTeX 2.9.6630 64-bit)
entering extended mode

(../../../.././gmp.texi
(C:\libGMP-6.1.99-dev\build\doc\texinfo.tex
Loading texinfo [version 2017-06-04.19]: pdf, fonts, markup, glyphs,
page headings, tables, conditionals, indexing, sectioning, toc, environments,
defuns, macros, cross references, insertions,
("C:\Program Files\PrgDev\MiKTeX\texmfs\install\tex\generic\epsf\epsf.tex"
This is `epsf.tex' v2.7.4 <14 February 2011>
) localization, formatting, and turning on texinfo input format.)
(C:\libGMP-6.1.99-dev\build\doc\version.texi)
Writing index file gmp.fn
[1{C:/Program Files/PrgDev/MiKTeX/texmfs/data/pdftex/config/pdftex.map}]
(gmp.aux) [2] (gmp.toc [-1] [-2] [-3]) [-4] (gmp.toc) (gmp.toc)
(GNU MP Copying Conditions)
Writing index file gmp.cp
Chapter 1 [1] Chapter 2 [2] [3] [4]
Underfull \hbox (badness 10000) in paragraph at lines 826--838
 []@textrm SPARC: `@texttt sparc[]@textrm '[], `@texttt sparcv8[]@textrm '[], `
@texttt microsparc[]@textrm '[], `@texttt supersparc[]@textrm '[], `@texttt spa
rcv9[]@textrm '[],
[5] [6] [7] [8] [9] [10] [11] [12] [13] [14] [15] Chapter 3 [16] [17] [18]
[19]
Underfull \hbox (badness 7168) in paragraph at lines 2169--2173
 []@textrm If con-fig-ured with @texttt --enable-alloca=malloc-notreentrant[] @
textrm (or with @texttt --enable-
[20]
Writing index file gmp.vr
[21]
Underfull \hbox (badness 7576) in paragraph at lines 2370--2377
 [][][][]@textrm The `@texttt perl[]@textrm '[] sub-di-rec-tory is a com-pre-he
n-sive perl in-ter-face to GMP. See
[22] [23] [24] [25] [26] [27] Chapter 4 [28] Chapter 5 [29] [30] [31] [32]
[33] [34] [35] [36] [37] [38] [39] [40] [41] [42] [43] [44] [45] Chapter 6
[46] [47] [48] [49] Chapter 7 [50] [51] [52] [53] [54] [55] [56] [57]
Chapter 8 [58] [59] [60] [61] [62] [63] [64] [65] [66] [67] [68] [69]
Chapter 9 [70] [71] Chapter 10 [72] [73] [74] [75] [76] Chapter 11 [77]
[78] [79] [80] Chapter 12 [81] [82] [83] [84] [85] [86] [87] [88] [89]
Chapter 13 [90] [91] Chapter 14 [92] [93] Chapter 15 [94]
Underfull \hbox (badness 10000) detected at line 7763
|
[95] [96] [97] [98] [99] [100] [101] [102] [103] [104] [105] [106] [107]
[108] [109] [110] [111] [112] [113] [114] [115] [116] [117] [118] Chapter 16
[119] [120] [121] [122] [123] Appendix A [124] [125] Appendix B [126] [127]
Appendix C [128]
(C:\libGMP-6.1.99-dev\build\doc\fdl-1.3.texi [129]
[130] [131] [132] [133] [134]) (Concept Index) [135]
! Missing number, treated as zero.
<to be read again>
                   }
@finishentry ...@global @setbox @boxB = @hbox {#1}
                                                  @ifdim @wd @boxB = 0pt @nu...

@body ...i @indexinputprocessing @thisline @ifeof
                                                  1@else @let @thisline @nex...

@next ->@let @next =@relax @body
                                 @let @next =@loopdoxxx @fi @next
@\printindex ... @let @thisline @nextline @repeat
                                                  @enddoublecolumns @fi @fi ...
l.10927 @printindex cp

! Missing } inserted.
<inserted text>
                }
<to be read again>
                   @endgroup
l.10927 @printindex cp

)
! Emergency stop.
<*> \nonstopmode \input ../../../.././gmp.texi

!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on gmp.log.
/usr/bin/texi2dvi: pdfetex exited with bad status, quitting.
make[1]: *** [Makefile:456: gmp.pdf] Error 1
make[1]: Leaving directory '/c/libGMP-6.1.99-dev/build/doc'
make: *** [Makefile:963: install-pdf-recursive] Error 1
```
A similar for MPIR (and presumably MPFR).

Reproduced for:
* builds using pdfTeX, Version 3.14159265-2.6-1.40.19 (MiKTeX 2.9.6630 64-bit),

not reproduced for:
* builds using pdfTeX, Version 3.14159265-2.6-1.40.18 (MiKTeX 2.9.6400 64-bit).

Environment:
* Windows 10 x64,
* mingw-w64 x86_64 7.3.0,
* ICC 2018 Update 2,
* MSVC 2017 15.5.0,
* Windows SDK 10.0.16299.15,
* MSYS2 20170918 with texinfo 6.3-1 installed,
* MiKTeX 2.9.6630 64-bit with recent updates and all available packages,
* GMP-6.1.99-dev (17595), MPIR 3.0.0.

Best,

Alexander

**Comment by edocevoli** [comment] 2018-04-01 13:28
I cannot reproduce the bug with the given information.

If you need a fix for this bug: please write a minimal example input file which can be used to reproduce the bug. Don't expect that we have `make` or `makeinfo` in our toolchain.

**Closed by edocevoli** 2018-04-01 13:28 UTC

**Comment by sav-ix** [comment] 2018-04-01 14:42
Made a testcase, based on GMP sources [miktex_gmp_documentation_build_testcase.zip](https://github.com/MiKTeX/miktex/files/1866414/miktex_gmp_documentation_build_testcase.zip).
Let me know, if there would be gaps in reproducing steps.

**Comment by sav-ix** [comment] 2018-05-15 08:27
Hello,

Any news on this? Or any additional information required in order to reopen this issue?

**Comment by edocevoli** [comment] 2018-05-15 09:18
No, there are no news, i.e., I am not working on this issue. If you feel that this is a MiKTeX-specific bug, then I am sorry.
