### ISSUE TITLE
pdflatex fails with shortened Windows paths

### ISSUE THREAD

**Issue by kgoettler** [MiKTeX/miktex#583] opened 2020-07-10 14:46 UTC
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

New installation of MiKTeX (20.6.29) on Windows 10. `pdflatex` fails with shortened (8.3) Windows paths. I don't have this issue on my old computer, which is running MiKTeX 2.9.7300.

I found a reference to a similar bug in the [tex-live mailing list](https://tug.org/pipermail/tex-live/2014-June/035507.html), but they claim it was fixed there in 2015. 

## Inputs and Log File
[test.zip](https://github.com/MiKTeX/miktex/files/4903707/test.zip)
[pdflatex.log](https://github.com/MiKTeX/miktex/files/4903766/pdflatex.log)

## Step-by-Step Instructions

Using the full path works fine
```cmd
> pdflatex C:\Users\kgoettler\AppData\Local\Temp\test.tex
```

However, using the shortened path (e.g. what Windows uses in the `%TEMP%` environment variable) does not:
```cmd
> pdflatex C:\Users\KGOETT~1\AppData\Local\Temp\test.tex

This is pdfTeX, Version 3.14159265-2.6-1.40.21 (MiKTeX 20.6.29)
entering extended mode
! I can't find file `C:/Users/KGOETT'.
<to be read again>
                   \protect
<*> C:/Users/KGOETT~
                    1/AppData/Local/Temp/test.tex
Please type another input file name: X
(C:\Users\kgoettler\AppData\Local\Programs\MiKTeX\tex/latex/tools\X.tex
LaTeX2e <2020-02-02> patch level 5
L3 programming layer <2020-06-18>
```

## Configuration Report
```
> initexmf --report
ReportDate: 2020-07-10 10:20:47
CurrentVersion: 20.6.29
SetupDate: 2020-07-08 11:05:00
SetupVersion: 20.6.29
Configuration: Regular
GitInfo: 4164370 / 2020-06-30 20:16:39
OS: Windows 10 Pro, 64-bit, build 19041
SharedSetup: no
LinkTargetDirectory: C:\Users\kgoettler\AppData\Local\Programs\MiKTeX\miktex\bin\x64
PathOkay: yes
LastUpdateCheck: 2020-07-10 10:02:36
LastUpdate: 2020-07-10 10:19:04
LastUpdateDb: 2020-07-10 10:02:35
SystemAdmin: no
RootPrivileges: no
AdminMode: no
Root0: C:\Users\kgoettler\AppData\Roaming\MiKTeX
Root1: C:\Users\kgoettler\AppData\Local\MiKTeX
Root2: C:\Users\kgoettler\AppData\Local\Programs\MiKTeX
Root3: C:\ProgramData\MiKTeX
Root4: C:\Program Files\MiKTeX
UserInstall: C:\Users\kgoettler\AppData\Local\Programs\MiKTeX
UserConfig: C:\Users\kgoettler\AppData\Roaming\MiKTeX
UserData: C:\Users\kgoettler\AppData\Local\MiKTeX
CommonInstall: C:\Program Files\MiKTeX
CommonConfig: C:\ProgramData\MiKTeX
CommonData: C:\ProgramData\MiKTeX

> pdflatex --version
MiKTeX-pdfTeX 4.0.1 (MiKTeX 20.6.29)
© 1982 D. E. Knuth, © 1996-2020 Hàn Thế Thành
TeX is a trademark of the American Mathematical Society.
using bzip2 version 1.0.6, 6-Sept-2010
compiled with curl version 7.61.1; using libcurl/7.61.1 WinSSL
compiled with expat version 2.2.6; using expat_2.2.6
compiled with jpeg version 9.3
compiled with liblzma version 50020042; using 50020042
compiled with libpng version 1.6.37; using 1.6.37
compiled with libressl version LibreSSL 2.8.2; using LibreSSL 2.8.2
compiled with MiKTeX Application Framework version 4.0; using 4.0
compiled with MiKTeX Core version 4.0; using 4.0
compiled with MiKTeX Archive Extractor version 4.0; using 4.0
compiled with MiKTeX Package Manager version 4.0; using 4.0
compiled with poppler version 0.60.1
compiled with uriparser version 0.9.2
compiled with zlib version 1.2.11; using 1.2.11
```

**Comment by edocevoli** [comment] 2020-07-10 15:16
Duplicate of #573

**Closed by edocevoli** 2020-07-10 15:16 UTC
