### ISSUE TITLE
while "apt-get update"

### ISSUE THREAD

**Issue by HatcherRobotics** [MiKTeX/miktex#803] opened 2021-05-02 13:03 UTC
"Skipping acquire of configured file 'universe / binary-i386 / Packages' as
repository 'http://miktex.org/download/ubuntu bionic InRelease' doesn't
support architecture 'i386'"

**Comment by edocevoli** [comment] 2021-05-02 19:26
Duplicate of #775

**Closed by edocevoli** 2021-05-02 19:26 UTC
