### ISSUE TITLE
The package definition file could not be parsed

### ISSUE THREAD

**Issue by RogueWarlock** [MiKTeX/miktex#145] opened 2018-06-14 15:40 UTC
Hello,

I am trying to get MiKTeX to update on a Windows 10 Enterprise v1709 laptop. I am getting the following error:

The package definition file could not be parsed.

Data:
path="C:\Users\username\AppData\Local\Temp\2\mik78743\cellprops.tpm", line="2", column="1124"

We are using the latest version downloaded from the website. I have ensured that the user has admin privileges. We have tried installing for all users, and only that user.  We have tried running the application as admin. I installed it on two other computers, and cannot duplicate this issue. This laptop is a fresh build. I have not been able to find any fixes for this. Any suggestions are appreciated. 

Thank you,

Charles

**Comment by edocevoli** [comment] 2018-06-14 16:21
Duplicate of miktex/miktex-packaging#34

**Closed by edocevoli** 2018-06-14 16:21 UTC
