### ISSUE TITLE
MiKTeX error on ubuntu

### ISSUE THREAD

**Issue by aochtman** [MiKTeX/miktex#15] opened 2017-10-05 10:53 UTC
I have installed MiKTeX on my ubuntu server with the goal to create PDF. I receive this error:

```
Sorry, but pdflatex did not succeed.

You may want to visit the MiKTeX project page, if you need help.
terminate called after throwing an instance of 'MiKTeX::Core::MiKTeXException'
  what():  MiKTeX encountered an internal error.

pandoc: Error producing PDF
```

See for more details here: https://stackoverflow.com/questions/46582088/pandoc-error-producing-pdf/46582978#46582978

**Comment by edocevoli** [comment] 2017-10-05 11:00
Thank you. Please attach the log files. Should be here:

    ~/.miktex/data/miktex/log/

And it would be nice if you provide a minimal test case.

**Comment by aochtman** [comment] 2017-10-05 11:24
I am sorry but I am quite new to ubuntu. 

I am currently in the /usr directory. ls outputs the following:
- bin
- games
- include
- lib
- libexec
- local
- sbin
- share
- src

**Comment by edocevoli** [comment] 2017-10-05 11:39
Thank you. So it seems that you cannot provide more information? Too bad...

Let's try again. Enter this command:

    tar -cvzf logfiles.tar.gz ~/.miktex/texmfs/data/miktex/log/*

Then attach `logfiles.tar.gz` to this ticket. Thank you!

**Comment by aochtman** [comment] 2017-10-05 12:20
[logfiles.tar.gz](https://github.com/MiKTeX/miktex/files/1359251/logfiles.tar.gz)

**Comment by edocevoli** [comment] 2017-10-05 12:31
Thank you. So it seems that everything is alright (no error messages in the log files). Since you provided no minimal test case, I cannot work on this issue effectively and I will close this ticket. If you have more info available: you can add comments and attach files.

**Closed by edocevoli** 2017-10-05 12:31 UTC
Labels: invalid

**Comment by aochtman** [comment] 2017-10-05 12:54
**Setup**

- Ubuntu
- Installed pandoc
- Installed MikTeX:

```
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys D6BC243565B2087BC3F897C9277A7293F59E4889

echo "deb http://miktex.org/download/ubuntu xenial universe" | sudo tee /etc/apt/sources.list.d/miktex.list

sudo apt-get update

sudo apt-get install miktex
```

**R-code**
```
# Set working directory
setwd("/var/www/html/test_Knitr")

# Create .md, .html, and .pdf files
print("Debug1: packages loaded")

setwd("/var/www/html/DATA/test")
knit("/var/www/html/test_Knitr/reporting_style.Rmd")
print("Debug2: knit succesfull")

setwd("/var/www/html/DATA/test")
print("Debug3: setwd successfull")

markdownToHTML('/var/www/html/DATA/test/reporting_style.md', '/var/www/html/DATA/test/reporting_style.html', options=c("use_xhml"))
print("Debug4: markdownToHTML succesfull")

system("pandoc -s /var/www/html/DATA/test/reporting_style.html -o /var/www/html/DATA/test/reporting_style.pdf")
print("Debug5: pandoc succesfull")
```

**reporting_style.Rmd**
```
---
title: "Reporting template"
output: html_document
---


## R Markdown

This is an R Markdown document. Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents. 
```

**Problem**
The function runs perfectly until it reaches the last part `system("pandoc.."` Here I receive an error message:

```
Sorry, but pdflatex did not succeed.

You may want to visit the MiKTeX project page, if you need help.
terminate called after throwing an instance of 'MiKTeX::Core::MiKTeXException'
  what():  MiKTeX encountered an internal error.

pandoc: Error producing PDF
```

Is this sufficient?

**Comment by edocevoli** [comment] 2017-10-05 13:53
No, this does not help me to reproduce the issue. Quoting [this site](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html):

"_The aim of the exercise is to enable them to reproduce the problem. You want the programmer to run their own copy of the program, do the same things to it, and make it fail in the same way. When they can see the problem happening in front of their eyes, then they can deal with it._

_So tell them exactly what you did. If it's a graphical program, tell them which buttons you pressed and what order you pressed them in. If it's a program you run by typing a command, show them precisely what command you typed. Wherever possible, you should provide a verbatim transcript of the session, showing what commands you typed and what the computer output in response._

_Give the programmer all the input you can think of. If the program reads from a file, you will probably need to send a copy of the file. If the program talks to another computer over a network, you probably can't send a copy of that computer, but you can at least say what kind of computer it is, and (if you can) what software is running on it._"
