### ISSUE TITLE
Failed to build 21.6.28 on linux

### ISSUE THREAD

**Issue by ccat3z** [MiKTeX/miktex#860] opened 2021-06-30 02:58 UTC
- [X] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

Failed to build 21.6.28 on linux. Here is the error log. I'm not familiar with C++, it seems that `unxFileSystemWatcher::WatchDirectories()` isn't implemented.

```
[  5%] Building CXX object Libraries/MiKTeX/Core/shared/CMakeFiles/miktex-core.dir/__/FileSystemWatcher/unx/unxFileSystemWatcher.cpp.o
In file included from /usr/include/c++/11.1.0/memory:76,
                 from /home/c0ldcat/Documents/arch-repo/miktex-git/src/miktex/Libraries/MiKTeX/Trace/include/miktex/Trace/TraceStream.h:29,
                 from /home/c0ldcat/Documents/arch-repo/miktex-git/src/miktex/Libraries/MiKTeX/Trace/include/miktex/Trace/TraceStream:24,
                 from /home/c0ldcat/Documents/arch-repo/miktex-git/src/miktex/Libraries/MiKTeX/Core/internal.h:31,
                 from /home/c0ldcat/Documents/arch-repo/miktex-git/src/miktex/Libraries/MiKTeX/Core/FileSystemWatcher/unx/unxFileSystemWatcher.cpp:24:
/usr/include/c++/11.1.0/bits/unique_ptr.h: In instantiation of ‘typename std::_MakeUniq<_Tp>::__single_object std::make_unique(_Args&& ...) [with _Tp = MiKTeX::ABF3880A6239B84E87DC7E727A8BBFD4::unxFileSystemWatcher; _Args = {}; typename std::_MakeUniq<_Tp>::__single_object = std::unique_ptr<MiKTeX::ABF3880A6239B84E87DC7E727A8BBFD4::unxFileSystemWatcher, std::default_delete<MiKTeX::ABF3880A6239B84E87DC7E727A8BBFD4::unxFileSystemWatcher> >]’:
/home/c0ldcat/Documents/arch-repo/miktex-git/src/miktex/Libraries/MiKTeX/Core/FileSystemWatcher/unx/unxFileSystemWatcher.cpp:35:43:   required from here
/usr/include/c++/11.1.0/bits/unique_ptr.h:962:30: error: invalid new-expression of abstract class type ‘MiKTeX::ABF3880A6239B84E87DC7E727A8BBFD4::unxFileSystemWatcher’
  962 |     { return unique_ptr<_Tp>(new _Tp(std::forward<_Args>(__args)...)); }
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/c0ldcat/Documents/arch-repo/miktex-git/src/miktex/Libraries/MiKTeX/Core/FileSystemWatcher/unx/unxFileSystemWatcher.cpp:26:
/home/c0ldcat/Documents/arch-repo/miktex-git/src/miktex/Libraries/MiKTeX/Core/FileSystemWatcher/unx/unxFileSystemWatcher.h:28:7: note:   because the following virtual functions are pure within ‘MiKTeX::ABF3880A6239B84E87DC7E727A8BBFD4::unxFileSystemWatcher’:
   28 | class unxFileSystemWatcher :
      |       ^~~~~~~~~~~~~~~~~~~~
In file included from /home/c0ldcat/Documents/arch-repo/miktex-git/src/miktex/Libraries/MiKTeX/Core/FileSystemWatcher/unx/unxFileSystemWatcher.h:24,
                 from /home/c0ldcat/Documents/arch-repo/miktex-git/src/miktex/Libraries/MiKTeX/Core/FileSystemWatcher/unx/unxFileSystemWatcher.cpp:26:
/home/c0ldcat/Documents/arch-repo/miktex-git/src/miktex/Libraries/MiKTeX/Core/FileSystemWatcher/unx/../FileSystemWatcherBase.h:62:31: note:     ‘virtual void MiKTeX::ABF3880A6239B84E87DC7E727A8BBFD4::FileSystemWatcherBase::WatchDirectories()’
   62 |   virtual void MIKTEXTHISCALL WatchDirectories() = 0;
      |                               ^~~~~~~~~~~~~~~~
In file included from /usr/include/c++/11.1.0/memory:76,
                 from /home/c0ldcat/Documents/arch-repo/miktex-git/src/miktex/Libraries/MiKTeX/Trace/include/miktex/Trace/TraceStream.h:29,
                 from /home/c0ldcat/Documents/arch-repo/miktex-git/src/miktex/Libraries/MiKTeX/Trace/include/miktex/Trace/TraceStream:24,
                 from /home/c0ldcat/Documents/arch-repo/miktex-git/src/miktex/Libraries/MiKTeX/Core/internal.h:31,
                 from /home/c0ldcat/Documents/arch-repo/miktex-git/src/miktex/Libraries/MiKTeX/Core/FileSystemWatcher/unx/unxFileSystemWatcher.cpp:24:
/usr/include/c++/11.1.0/bits/unique_ptr.h: In instantiation of ‘typename std::_MakeUniq<_Tp>::__single_object std::make_unique(_Args&& ...) [with _Tp = MiKTeX::ABF3880A6239B84E87DC7E727A8BBFD4::unxFileSystemWatcher; _Args = {}; typename std::_MakeUniq<_Tp>::__single_object = std::unique_ptr<MiKTeX::ABF3880A6239B84E87DC7E727A8BBFD4::unxFileSystemWatcher, std::default_delete<MiKTeX::ABF3880A6239B84E87DC7E727A8BBFD4::unxFileSystemWatcher> >]’:
/home/c0ldcat/Documents/arch-repo/miktex-git/src/miktex/Libraries/MiKTeX/Core/FileSystemWatcher/unx/unxFileSystemWatcher.cpp:35:43:   required from here
/usr/include/c++/11.1.0/bits/unique_ptr.h:962:30: error: invalid new-expression of abstract class type ‘MiKTeX::ABF3880A6239B84E87DC7E727A8BBFD4::unxFileSystemWatcher’
  962 |     { return unique_ptr<_Tp>(new _Tp(std::forward<_Args>(__args)...)); }
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/c0ldcat/Documents/arch-repo/miktex-git/src/miktex/Libraries/MiKTeX/Core/FileSystemWatcher/unx/unxFileSystemWatcher.cpp:26:
/home/c0ldcat/Documents/arch-repo/miktex-git/src/miktex/Libraries/MiKTeX/Core/FileSystemWatcher/unx/unxFileSystemWatcher.h:28:7: note:   because the following virtual functions are pure within ‘MiKTeX::ABF3880A6239B84E87DC7E727A8BBFD4::unxFileSystemWatcher’:
   28 | class unxFileSystemWatcher :
      |       ^~~~~~~~~~~~~~~~~~~~
In file included from /home/c0ldcat/Documents/arch-repo/miktex-git/src/miktex/Libraries/MiKTeX/Core/FileSystemWatcher/unx/unxFileSystemWatcher.h:24,
                 from /home/c0ldcat/Documents/arch-repo/miktex-git/src/miktex/Libraries/MiKTeX/Core/FileSystemWatcher/unx/unxFileSystemWatcher.cpp:26:
/home/c0ldcat/Documents/arch-repo/miktex-git/src/miktex/Libraries/MiKTeX/Core/FileSystemWatcher/unx/../FileSystemWatcherBase.h:62:31: note:     ‘virtual void MiKTeX::ABF3880A6239B84E87DC7E727A8BBFD4::FileSystemWatcherBase::WatchDirectories()’
   62 |   virtual void MIKTEXTHISCALL WatchDirectories() = 0;
      |                               ^~~~~~~~~~~~~~~~
make[2]: *** [Libraries/MiKTeX/Core/static/CMakeFiles/core-static.dir/build.make:258: Libraries/MiKTeX/Core/static/CMakeFiles/core-static.dir/__/FileSystemWatcher/unx/unxFileSystemWatcher.cpp.o] Error 1
```

**Comment by edocevoli** [comment] 2021-06-30 10:05
Yes, `FileSystemWatcher` is a new class which has not been implemented for Linux (yet).

**Comment by aabacchus** [comment] 2021-06-30 22:43
Same issue here. https://0x0.st/-fsO.txt

**Comment by Richardk2n** [comment] 2021-07-02 08:08
Am I right in the assumption, that `FileSystemWatcher` is new in 21.6.28 and did not yet exist in 21.6?
If yes, how is my issue (#864) a duplicate of this?

**Comment by edocevoli** [comment] 2021-07-02 08:37
Yes, `FileSystemWatcher` is new. I guess #864 is a duplicate. Don't know for sure. On the other hand, #864 does not contain any useful information. No platform info. Not even the C/C++ error message which caused the build failure. Prime example of a bad bug report. Not worth working on it.

**Comment by Richardk2n** [comment] 2021-07-02 10:09
> 
> 
> Yes, `FileSystemWatcher` is new. I guess #864 is a duplicate. Don't know for sure. On the other hand, #864 does not contain any useful information. No platform info. Not even the C/C++ error message which caused the build failure. Prime example of a bad bug report. Not worth working on it.

If the cause of this issue did not exist in the version my issue talks about, i guess it's reasonable to assume, that it is not a duplicate.
Neither your issue template nor your how-to link provide information about what platform info to provide (except from maybe running initexmf, which seems to not exist on my system). If one is not a C developer, it is hard to know what you need without being told. I provided the last lines of the log, which indeed contain no (usable) error messages. There are errors/warnings way earlier in the log, but afterwards all seems to be fine. As I have seen this in earlier versions, i figured, that this is fine and only provided the end of the log, which does not contain error messages. If you want the full log, i can provide it. If you maybe want the content of some other log, that i don't even know exists, please tell me, I can provide it.

I followed the instructions to report a bug, as well as I could and tried to mimic other reports. I am sorry, if this leads to a bad report, but there is not much I can do about that without additional information.

So could you please tell me what you would need to work on it, instead of just closing it and removing the possibility to follow this up?

**Comment by edocevoli** [comment] 2021-07-02 10:19
21.6.28 was a Windows-only release (there are no Linux packages). MiKTeX 21.7 will be build on the supported Linux platforms. So this issue will be fixed "automatically".

**Comment by aabacchus** [comment] 2021-07-02 14:36
> If you want the full log, i can provide it.

That would be useful. Most likely, you've been building MiKTeX with multiple jobs (`-jN`), so when the actual error occurred, a few jobs had to finish, so the last few lines of your log won't be the actual error - it's probably close to the first "waiting for unfinished jobs". I could build 21.6 fine but not 21.6.28, so it's probably not a duplicate of this bug.

@edocevoli - in the future, could you make it clearer which releases are 'Windows-only' - there wasn't anything in the release notes and I'm not sure what you mean by no Linux packages, since we're talking about build errors.

**Comment by Richardk2n** [comment] 2021-07-02 16:24
Tank you very much, I did not think about that.

[fulllog.txt](https://github.com/MiKTeX/miktex/files/6755809/fulllog.txt)

The line `Es wird auf noch nicht beendete Prozesse gewartet....` (some of my log is apprently in german) even appears twice.

And right above the first occurence is something, that reports to be an error:
```
[ 64%] Linking CXX static library ../../../../sandbox/miktex/bin/linux-x86_64/libodvicopy.a
/var/tmp/pamac-build-richard/miktex/src/miktex-21.6/Programs/TeXAndFriends/omega/otps/source/outocp.c: In Funktion »ctp_abort«:
/var/tmp/pamac-build-richard/miktex/src/miktex-21.6/Programs/TeXAndFriends/omega/otps/source/outocp.c:93:3: Fehler: Format ist kein Zeichenkettenliteral, und keine Formatargumente [-Werror=format-security]
   93 |   fprintf(stderr, s);
      |   ^~~~~~~
[ 64%] Building CXX object Programs/TeXAndFriends/omega/otps/CMakeFiles/miktex-outocp.dir/__/__/__/__/Libraries/MiKTeX/etc/wrapper.cpp.o
cc1: Einige Warnungen werden als Fehler behandelt
make[2]: *** [Programs/TeXAndFriends/omega/otps/CMakeFiles/miktex-outocp.dir/build.make:76: Programs/TeXAndFriends/omega/otps/CMakeFiles/miktex-outocp.dir/source/outocp.c.o] Fehler 1
make[2]: *** Es wird auf noch nicht beendete Prozesse gewartet....

```
I am sorry for the german error messages.

**Comment by edocevoli** [comment] 2021-07-03 09:35
@aabacchus You are absolutely right. Such issues should be documented in the changelog. And the source code shouldn't have been published.

**Closed** 2021-07-19 07:12 UTC
Labels: linux
