### ISSUE TITLE
Miktex Error Report - Miktex Concole

### ISSUE THREAD

**Issue by K4Werri** [MiKTeX/miktex#398] opened 2019-10-20 08:11 UTC
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

After installing updates, I cannot switch to Admin mode in the console. A message box pop[ up appears containing the following:

MiKTeX encountered an internal error.

with details ...

index="4294967295".

Platform is Windows 10.

Reproduction.
1. start the console
2. switch to admin mode
3. failure as described above

[miktex-report.txt](https://github.com/MiKTeX/miktex/files/3747634/miktex-report.txt)

**Comment by edocevoli** [comment] 2019-10-20 08:44
Thank you for the report. This will be fixed with one of the next updates. To bring back on course, I will soon add a hotfix to this ticket.

**Comment by edocevoli** [comment] 2019-10-20 10:05
The attached Zip archive contains a corrected version of the MiKTeX core run-time library (64-bit variant):

```
Archive:  hotfix.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
  2357760  10-20-2019 11:45   MiKTeX209-core.dll
---------                     -------
  2357760                     1 file
```

The file must be copied to the MiKTeX bin directory (usually `C:\Program Files\MiKTeX 2.9\miktex\bin\x64`).

[hotfix.zip](https://github.com/MiKTeX/miktex/files/3747694/hotfix.zip)
SHA256: `3EC570B16D3EE4C8BD6880AB5886A6A3713B746DFEDED1E25D3F66942B1EE971`

**Comment by pathmissing** [comment] 2019-10-20 10:17
@edocevoli Thank you for your dedication to fix issues so quickly! Is it expected behaviour that the whole MiKTeX repository is currently unavailable due to this issue?

**Comment by edocevoli** [comment] 2019-10-20 10:25
Yes, the repository has been taken offline until tomorrow.

**Comment by josegaspar999** [comment] 2019-10-20 10:31
I was caught by this offline state, could not compile due to missing "relsize.sty". My temporary workaround is a direct download from CTAN to the folder of the Latex file.

**Comment by K4Werri** [comment] 2019-10-21 02:34
Thanks for the quick fix. I can now switch to admin mode.

K.

**Closed** 2019-10-21 11:28 UTC
Labels: bug

**Comment by HeinerRichter** [comment] 2019-10-23 05:19
Is this a fix for the w32-Version too?

**Comment by edocevoli** [comment] 2019-10-23 07:48
The 32-bit version can be retrieved from the MiKTeX package repository.
