### ISSUE TITLE
Error "MiKTeX cannot retrieve attributes for the directory 'C:\WINDOWS\system32\config\systemprofile'.

### ISSUE THREAD

**Issue by fo454684** [MiKTeX/miktex#653] opened 2020-11-04 19:21 UTC
We lost 2 mandays with the exact same bug which was reported 6 months ago and before.

https://github.com/MiKTeX/miktex/issues/522

*IT IS miktex BUG*. No reason to access that. Instead of trying to solve that problem the ticket was arrogantly closed. If we could dump miktex, we would do it instantly but on Windows it's quite hard. Please, again, would you mind to somehow try and check that bug report seriously? Many companies run TeX through ASP.NET etc.

**Comment by edocevoli** [comment] 2020-11-04 21:35
Duplicate of #522

**Closed** 2020-11-04 21:35 UTC

**Comment by edocevoli** [comment] 2020-11-04 21:37
To quote myself:

> Sorry, but without the log files it is not possible to work on this issue. I am out.
