### ISSUE TITLE
miktexsetup:  Unknown/unsupported setup task: uninstall

### ISSUE THREAD

**Issue by fruholm** [MiKTeX/miktex#657] opened 2020-11-06 14:57 UTC
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

I have downloaded the latest version of miktexsetup for Win10 (miktexsetup-4.0-x64.zip) for a deployment package in SCCM for MikTeX 20.11.

I ran: 
"...\Downloads\miktexsetup.exe --verbose --shared=yes uninstall", as stated on https://docs.miktex.org/manual/miktexsetup.html
Gives:
"miktexsetup.exe: Unknown/unsupported setup task: uninstall"

Tried the same with the miktexsetup.exe from our last package (for 2.9) - it gives:
"initializing setup service...
loading C:\Program Files\MiKTeX 2.9\miktex\config\uninst.log...
removing links...
Collecting linked executables in target directory "C:\Program Files\MiKTeX\miktex/bin/x64"...
unregistering file types...
Windows API error 123: The filename, directory name, or volume label syntax is incorrect.

cleaning system PATH...
unregistering components...
removing MiKTeX files from C:\ProgramData\Microsoft\Windows\Start Menu\Programs...
removing root directories...
removing registry settings...
removing 0 registry values..."

"uninstall" is recognized but obviously the rest doesn't work.

**Comment by edocevoli** [comment] 2020-11-06 15:37
Duplicate of #596

**Closed by edocevoli** 2020-11-06 15:37 UTC
