### ISSUE TITLE
Error when updating

### ISSUE THREAD

**Issue by BeerStud** [MiKTeX/miktex#177] opened 2018-08-16 11:03 UTC
**Please note: we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide all the required information.**

Checklist:
- [ ] I am reporting a bug others will be able to reproduce
- [ ] I have installed the latest MiKTeX updates
- [ ] I have checked the MiKTeX log files

When attempting to update MiKTeX as an administrator, an error occurs. This was copied to the clipboard:

MiKTeX Problem Report
Message: The executed process did not succeed.
Data: fileName="C:\Program Files\MiKTeX 2.9\miktex/bin/x64\initexmf.exe", exitCode="1"
Source: Libraries\MiKTeX\Core\Process\Process.cpp
Line: 177
MiKTeX: 2.9
OS: Windows 10 Pro, 64-bit, build 17713
Invokers: 
SystemAdmin: yes
PowerUser: no
Root0: C:\Users\Gerard\AppData\Roaming\MiKTeX\2.9
Root1: C:\Users\Gerard\AppData\Local\MiKTeX\2.9
Root2: C:\ProgramData\MiKTeX\2.9
Root3: C:\Program Files\MiKTeX 2.9
UserInstall: C:\Users\Gerard\AppData\Roaming\MiKTeX\2.9
UserConfig: C:\Users\Gerard\AppData\Roaming\MiKTeX\2.9
UserData: C:\Users\Gerard\AppData\Local\MiKTeX\2.9
CommonInstall: C:\Program Files\MiKTeX 2.9
CommonConfig: C:\ProgramData\MiKTeX\2.9
CommonData: C:\ProgramData\MiKTeX\2.9

This is the second time this has occurred. I am running Windows 10 PRO/amd64,

[initexmf_admin.log](https://github.com/MiKTeX/miktex/files/2293397/initexmf_admin.log)

[miktex-console_admin.log](https://github.com/MiKTeX/miktex/files/2293425/miktex-console_admin.log)

**Comment by edocevoli** [comment] 2018-08-16 11:26
Duplicate of #174

**Closed by edocevoli** 2018-08-16 11:26 UTC
Labels: duplicate
