### ISSUE TITLE
A MiKTeX configuration file could not be loaded.

### ISSUE THREAD

**Issue by evensure** [MiKTeX/miktex#490] opened 2020-03-11 23:10 UTC
Hi,

I don't know if this is of relevance, but the last package I added was blkarray. Though, some example code didn't work and I wanted to check if the package was installed. Immediately, a message popped up telling me that something was wrong. 

I cannot update MiKTeX, anymore and deriving from older issues, I guess my package-manifests.ini file is corrupted. But in my case a different line is affected.
Here is the affected line (it begins with SPACE from the prior line):
`
 typically to be overlaid on an included graphic. The package requires a recent version of the package pst-node and some other pstricks-related material.`

This is the Error info (I only starred out my user name):

```
GENERAL MIKTEX INFORMATION
Date: 2020-03-11 23:51:26
MiKTeX: 2.9.7250
OS: Windows 10 Home, 64-bit, build 18363
SharedSetup: no
LinkTargetDirectory: C:\Users\*\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64
PathOkay: yes
LastUpdateCheck: 2020-02-04 14:08:00
LastUpdate: 2020-02-04 14:09:16
SystemAdmin: yes
RootPrivileges: no
AdminMode: no
Root0: C:\Users\*\AppData\Roaming\MiKTeX\2.9
Root1: C:\Users\*\AppData\Local\MiKTeX\2.9
Root2: C:\Users\*\AppData\Local\Programs\MiKTeX 2.9
Root3: C:\ProgramData\MiKTeX\2.9
Root4: C:\Program Files\MiKTeX 2.9
UserInstall: C:\Users\*\AppData\Local\Programs\MiKTeX 2.9
UserConfig: C:\Users\*\AppData\Roaming\MiKTeX\2.9
UserData: C:\Users\*\AppData\Local\MiKTeX\2.9
CommonInstall: C:\Program Files\MiKTeX 2.9
CommonConfig: C:\ProgramData\MiKTeX\2.9
CommonData: C:\ProgramData\MiKTeX\2.9
Invokers: non-existing/explorer

ERROR DETAILS
Program: C:\Users\*\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\miktex-console.exe
Source: Libraries\MiKTeX\Core\Cfg\Cfg.cpp:1052
Error: A MiKTeX configuration file could not be loaded.
Details: 
  file: C:\Users\*\AppData\Local\Programs\MiKTeX 2.9\miktex/config\package-manifests.ini
  line: 174950
  error: invalid value definition
```

**Comment by edocevoli** [comment] 2020-03-19 08:57
Duplicate of #290

**Closed** 2020-03-19 08:57 UTC
Labels: duplicate
