### ISSUE TITLE
'No hyphenation patterns were preloaded for(babel) the language `Russian' into the format' warning for builds on Windows

### ISSUE THREAD

**Issue by sav-ix** [MiKTeX/miktex#104] opened 2018-04-01 20:06 UTC
Hello, everyone,

For `.tex` builds using MiKTeX got warning:
```
No hyphenation patterns were preloaded for(babel) the language `Russian' into the format.
```
while appropriate package has been installed:
![miktex_babel_components](https://user-images.githubusercontent.com/3617101/38176909-161909de-3600-11e8-89bb-a47827d5a614.jpg)

and file `\texmfs\install\tex\latex\babel-russian\russianb.ldf` available in MiKTeX installation folder.
(though it's not `<textmf>/tex/generic/babel/contrib/russianb.ldf`, as mentioned in package [documentation](https://ctan.org/tex-archive/macros/latex/contrib/babel-contrib/russian))

A similar warning was [reported](https://tex.stackexchange.com/questions/417212/linux-miktex-no-hyphenation-patterns-were-preloaded-for-the-language) for `French` language too, which mean it reproducible on other systems.

Reproduced for:
* builds using pdfTeX, Version 3.14159265-2.6-1.40.19 (MiKTeX 2.9.6630 64-bit),

not reproduced for:
* builds using pdfTeX, Version 3.14159265-2.6-1.40.18 (MiKTeX 2.9.6400 64-bit).

Environment:
* Windows 10 x64,
* MiKTeX 2.9.6630 64-bit with recent updates and all available packages,
* TeXstudio 2.12.8.

Best,

Alexander

**Comment by edocevoli** [comment] 2018-04-01 21:45
I cannot reproduce the bug with the given information.
If you need a fix for this bug: please write a minimal example input file which can be used to reproduce the bug.

**Closed by edocevoli** 2018-04-01 21:45 UTC

**Comment by sav-ix** [comment] 2018-04-02 10:05
Sure. The testcase to reproduce this warning:
```
\documentclass[russian]{article}
\usepackage[T2A]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage[russian, english]{babel}

\begin{document}
Текст на русском.\par
\end{document}
```
Not sure about TeXworks, but TeXstudio prints it in log window:
![texstudio_babel_warning](https://user-images.githubusercontent.com/3617101/38192629-66f17104-3676-11e8-991e-2d30a2ee74db.png)
Can you re-open this issue?

**Comment by sav-ix** [comment] 2018-05-15 08:27
Hello,

Any news on this? Or any additional information required in order to reopen this issue?

**Comment by Enzoupi** [comment] 2018-08-31 13:30
I believe I have the same error in French...

**Comment by Mrkol** [comment] 2019-02-13 22:11
I am experiencing this as well with russian. Same testcase reproduces it.

**Comment by rrodrigueznt** [comment] 2020-04-12 08:22
Hi! Same test case reproduces it in a MacBook Air running macOS 10.12.6, MiKTeX: 2.9.7350, building using VS CODE with LaTeX Workshop 8.8.0 extension. Could I provide more information to help working out this issue? Thanks!

**Comment by edocevoli** [comment] 2020-04-12 11:17
@rrodrigueznt: if you can

- provide a minimal TeX input file which reproduces the issue
- locate MiKTeX log files
- zip them up
- attach the zip file to this issue

then you are my hero. All previous commentators were not able to do this.

**Comment by rrodrigueznt** [comment] 2020-04-12 22:01
@edocevoli: I can do this and anything else that could help!

- @sav-ix posted that minimal TeX file, didn't he? Please, find is attached here as a txt as tex is not accepted. [russian_dummy.txt](https://github.com/MiKTeX/miktex/files/4467232/russian_dummy.txt).
- please, find also attached [pdflatex.log](https://github.com/MiKTeX/miktex/files/4467224/pdflatex.log) and [latexmk.log](https://github.com/MiKTeX/miktex/files/4467223/latexmk.log), both log files modified when compiling the minimal TeX input file attached.
- also attached a VS Code screenshot showing the [error message](https://user-images.githubusercontent.com/1550835/79080968-75122800-7d19-11ea-8483-d33109a5b79b.png) in the _**Problems**_ console when compiling the same file.

Please, let me know how I could be of any further help. Thanks for your time!

**Comment by edocevoli** [comment] 2020-04-17 08:15
I still cannot reproduce the issue. Running `pdflatex russian_dummy.txt` yields a valid PDF. I am out.
