### ISSUE TITLE
Failed to build 21.6 on linux

### ISSUE THREAD

**Issue by Richardk2n** [MiKTeX/miktex#864] opened 2021-07-02 07:41 UTC
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

I cannot update miktex (installed via AUR), because the build fails.

```
[ 73%] Linking CXX executable ../../../sandbox/miktex/bin/linux-x86_64/miktex-dvisvgm
[ 73%] Built target miktex-dvisvgm
make: *** [Makefile:166: all] Fehler 2
==> FEHLER: Ein Fehler geschah in build().
    Breche ab...
```

**Comment by edocevoli** [comment] 2021-07-02 07:57
Thank you. This is a known issue.
Duplicate of #860

**Closed by edocevoli** 2021-07-02 07:57 UTC
