### ISSUE TITLE
MiKTeX console crushes on launch on Mac 

### ISSUE THREAD

**Issue by auromg** [MiKTeX/miktex#804] opened 2021-05-05 19:19 UTC
I'm having the problem issued in #491.
I don't attach the screenshots since they are exactly the same. I have removed everything under /Users/.../Library/Application Support/MiKTeX but it doesn't work.
I can't uninstall MiKTeX since the console crushes.
In the terminal, the command miktexsetup is not found. No problem to remove the application files.
Thanks for your help.

**Comment by edocevoli** [comment] 2021-05-05 19:26
Duplicate of #491

**Closed by edocevoli** 2021-05-05 19:26 UTC

**Comment by edocevoli** [comment] 2021-05-05 19:28
I have unlocked the other issue. You can attach new info there.
