### ISSUE TITLE
Link target directory cannot be moved

### ISSUE THREAD

**Issue by zomborid** [MiKTeX/miktex#1252] opened 2022-12-19 20:22 UTC
Version: Miktex Console 4.8, One MiKTeX Utility 1.5 (MiKTeX 22.12)
OS: Linux Mint 21

I tried to change Settings->Directories->Link target directory:
Error message: _One MiKTeX Utility failed for some reason. The output has been saved to a file._
File content: _Incorrect usage: unexpected command arguments_

The new directory definitely exists and has the correct content (moved from home directory as is).
I really dislike having a "bin" directory in my home.

I tried moving "bin" and adding it to the PATH, but that did not work.

Also in the howto section: https://miktex.org/howto/modify-path
_The environment variable PATH is usually correctly set when you install MiKTeX on a computer running Windows or Linux._
This message is not really helpful without actually telling how to add things to the PATH variable.

**Comment by edocevoli** [comment] 2023-01-17 10:08
Duplicate of #1172

**Closed by edocevoli** 2023-01-17 10:08 UTC
