### ISSUE TITLE
install miktex on ubuntu 18.04 LTS failed because of unmet dependencies

### ISSUE THREAD

**Issue by garylavayou** [MiKTeX/miktex#123] opened 2018-04-30 13:15 UTC
Miktex requires the following packages:
>  miktex : Depends: libhunspell-1.3-0 (>= 1.3.3) but it is not installable
           Depends: libicu55 (>= 55.1-1~) but it is not installable
           Depends: libmpfr4 (>= 3.1.3) but it is not installable
           Depends: libpng12-0 (>= 1.2.13-4) but it is not installable

As a result, Miktex could not be installed.
> E: Unable to correct problems, you have held broken packages.

However, in my system, there exist packages that have higher version, _i.e._
> libhunspell-1.6-0 (1.6.2-1)
   libicu60 (60.2-3ubuntu3)
   libmpfr6 (4.0.1-1)
   libpng16-16 (1.6.34-1)

and I cannot find the lower versions in the repository.

I suppose that Miktex could also run with these higher version packages. So I wonder if the dependencies could be updated.

**Comment by edocevoli** [comment] 2018-04-30 14:35
Duplicate of #120

**Closed by edocevoli** 2018-04-30 14:35 UTC
