### ISSUE TITLE
After update dialogue has small error in the text

### ISSUE THREAD

**Issue by andrewcrook** [MiKTeX/miktex#599] opened 2020-08-11 15:20 UTC
after clicking "Update now" and installing updates. You get the dialogue 

"MiKTeX Console needs to be close."

"close." should be replaced with "closed."

![Screenshot 2020-08-11 at 15 52 00](https://user-images.githubusercontent.com/803618/89915509-5b60ee80-dbee-11ea-8e79-50bcc21be6b6.png)

**Comment by edocevoli** [comment] 2020-08-11 15:30
Duplicate of #579

**Closed by edocevoli** 2020-08-11 15:30 UTC
