### ISSUE TITLE
Cannot install MikTeX 2.9 on Windows 7

### ISSUE THREAD

**Issue by vshetsov** [MiKTeX/miktex#281] opened 2019-03-14 14:14 UTC
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)
I installed the `basic-miktex-2.9.6942-x64.exe` on my notebook with Windows 7 (SP1) for all users. Then I tried to start MikTeX Console for updates. The console didn't appear, the Windows message "application was closed" appeared instead. The message contained the following "details" (I give the approximate translation, windows message was in russian):  
      `Name of event:	APPCRASH`  
      `Application:	miktex-console.exe`  
      `App.Version :	2.9.6941.0`  
      `Time:	5c2cafcc`  
      `Module coused error:	ucrtbase.DLL`  
      `Module version:	10.0.16299.15`  
      `Module time:	70f70cc4`  
      `Exception code:	40000015`  
      `shift:	000000000006b71f`  
      `OS version:	6.1.7601.2.1.0.768.3`  
      `Lang:	1049`  
      `Additional 1:	af6a`  
      `Additional 2:	af6ae5d70eb5d895e8e0cd11c437eaf5`  
      `Additional 3:	d6d4`  
      `Additional 4:	d6d4a85776943652d37fa09e84beeb71`  
I also tried to start Console as Administrator. Next I couldn't uninstall MikTeX from Windows control panel - it didn't work. I deleted MikTeX folder manually, and reinstall it for a single user. The same result.  
Next I tried to reinstall MikTex, starting the Setup Wisard "as administrator". Installation failed with a message:  
    `The executed process did not succeed.`  
    `Details: filename="C:\Program Files\MikTex 2.9\miktex\bin\x64\initexmf.exe", exitcode="1"`  
In a log-window I see the following:  
`Sorry, but "MiKTeX Configuration Utility" did not succeed for the following reason:`  
`Option --admin only makes sense for a shared MiKTeX setup.`  
Folder `miktex\log` was not created.

**Comment by edocevoli** [comment] 2019-03-14 17:27
This is a known issue (Duplicate of #239).

**Closed by edocevoli** 2019-03-14 17:27 UTC

**Comment by edocevoli** [comment] 2019-03-14 17:29
Duplicate of #239
