### ISSUE TITLE
PATH handled incorrectly on Windows for MiKTeX version of TexWorks (and others)

### ISSUE THREAD

**Issue by ghertlei** [MiKTeX/miktex#1089] opened 2022-04-15 10:08 UTC
- [X] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

This is actually a reopen of #777 with the problem now being debugged and identified.

The root cause is that SessionImpl::CreateChildEnvironment() treats the *names* of environment variables as being case-sensitive, but on Windows they are not. The code is looking for the "PATH" variable to check whether certain mandatory directories are there.
On Windows the path variable is normally called "Path" and the code therefore does not find it. As a consequence it creates a new environment variable named "PATH" with the desired directory(s), but the original content of "Path" is not there.

As a consequence, the environment of child processes now has two variables, "Path" and "PATH" (order more or less random).
When Windows is asked to execute a sub-process (pygmentize.exe in my case), it succeeds when "Path" comes first and fails otherwise.
The behavior can be verified by executing **\immediate\write18{set}** to print out the environment passed on to sub-processes.

It seems this piece of code did attract attention before as it is bracketed with "if (NoFixPath)". However, NoFixPath is only set for the MiKTeX setup executable.

Workaround (e.g. in a wrapper WinTexWorks.cmd script): (replaces Windows original variable "Path" by "PATH" to avoid the bug)

```
@echo off
set XP=%PATH%
set Path=
set PATH=%XP%

start /B TeXworks %*
```

General information:
TeXworks version: 0.6.7 (MiKTeX 22.3)
TeXworks obtained from: MiKTeX package 22.3
Operating system: Windows 10 20H2

**Comment by edocevoli** [comment] 2022-04-15 10:13
Duplicate of #926

**Closed by edocevoli** 2022-04-15 10:13 UTC
