### ISSUE TITLE
MikTex console won't launch

### ISSUE THREAD

**Issue by lfmcmillan** [MiKTeX/miktex#601] opened 2020-08-14 06:11 UTC
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

I've just done a brand new install of MikTex on a brand new Windows 10 computer and I've tried to run MikTex console after the install, and every single time I try to run it it complains "MikTex console is already running", but the console isn't running, and there are no Miktex processes in the Task Manager.

Essentially, MikTex is even more unusable for me than it was in my previous issue: https://github.com/MiKTeX/miktex/issues/461

**Comment by edocevoli** [comment] 2020-08-14 07:22
Duplicate of #461

**Closed by edocevoli** 2020-08-14 07:22 UTC
