### ISSUE TITLE
miktexsetup.exe 4.0 uninstall not working anymore

### ISSUE THREAD

**Issue by NickETH** [MiKTeX/miktex#639] opened 2020-10-12 13:26 UTC
Hi Developers,
with version 4.0 of miktexsetup.exe on Windows, the uninstall command is not working anymore.
Return message: miktexsetup.exe: Unknown/unsupported setup task: uninstall

Please fix this ASAP, without it, it is not possible, to automate the packaging for our deployment system.

Thank you.

BR, Nick

**Comment by edocevoli** [comment] 2020-10-12 13:39
Duplicate of #596

**Closed by edocevoli** 2020-10-12 13:39 UTC
