### ISSUE TITLE
xelatex segfault (Linux Mint)

### ISSUE THREAD

**Issue by qiuzhu** [MiKTeX/miktex#77] opened 2018-02-22 15:10 UTC
I just test the Miktex in linux mint and the .tex is :

> \documentclass{book}
>  \usepackage{ctex}   % only works when comment this line 
> \usepackage{amsmath}
> \usepackage{amsfonts}
> \usepackage{amssymb}
> \usepackage{graphicx}
> \begin{document}
> 	this is the demo for xelatex
>       Miktex  大法好
> 	\[E=mc^2\]
> \end{document}

when I compile using xelatex , and command says:
`Document Class: book 2014/09/29 v1.4h Standard LaTeX document class
(/home/lotus/.miktex/texmfs/install/tex/latex/base/bk10.clo))
(/home/lotus/.miktex/texmfs/install/tex/latex/ctex/ctex.sty
(/home/lotus/.miktex/texmfs/install/tex/latex/l3kernel/expl3.sty
(/home/lotus/.miktex/texmfs/install/tex/latex/l3kernel/expl3-code.tex)
(/home/lotus/.miktex/texmfs/install/tex/latex/l3kernel/l3xdvipdfmx.def))
(/home/lotus/.miktex/texmfs/install/tex/latex/l3packages/xparse/xparse.sty)
(/home/lotus/.miktex/texmfs/install/tex/latex/l3packages/l3keys2e/l3keys2e.sty)
(/home/lotus/.miktex/texmfs/install/tex/latex/ctex/ctexhook.sty)
(/home/lotus/.miktex/texmfs/install/tex/latex/ctex/ctexpatch.sty)
(/home/lotus/.miktex/texmfs/install/tex/latex/base/fix-cm.sty
(/home/lotus/.miktex/texmfs/install/tex/latex/base/ts1enc.def))
(/home/lotus/.miktex/texmfs/install/tex/latex/ms/everysel.sty)
(/home/lotus/.miktex/texmfs/install/tex/latex/ctex/config/ctexopts.cfg)
(/home/lotus/.miktex/texmfs/install/tex/latex/ctex/engine/ctex-engine-xetex.def
(/home/lotus/.miktex/texmfs/install/tex/xelatex/xecjk/xeCJK.sty
(/home/lotus/.miktex/texmfs/install/tex/latex/l3packages/xtemplate/xtemplate.st
y) (/home/lotus/.miktex/texmfs/install/tex/latex/fontspec/fontspec.sty
(/home/lotus/.miktex/texmfs/install/tex/latex/fontspec/fontspec-xetex.sty
(/home/lotus/.miktex/texmfs/install/tex/latex/base/fontenc.sty
(/home/lotus/.miktex/texmfs/install/tex/latex/base/tuenc.def))
(/home/lotus/.miktex/texmfs/install/tex/latex/fontspec/fontspec.cfg)))
(/home/lotus/.miktex/texmfs/install/tex/xelatex/xecjk/xunicode-addon.sty
(/home/lotus/.miktex/texmfs/install/tex/xelatex/xunicode/xunicode.sty[1]    19445 segmentation fault (core dumped)  xelatex document.tex
`
 ps: the ctex package  handles the Chinese char
i just test in windows miktex  version,it works

**Comment by edocevoli** [comment] 2018-02-24 17:32
I was able to reproduce the segfault. The following workaround should work: turn on the auto-installer via the commad-line option `--enable-installer`:

    xelatex --enable-installer document.tex

**Comment by qiuzhu** [comment] 2018-02-25 13:37
this workaround works ! I hope the next update will fix the bug

**Comment by edocevoli** [comment] 2018-04-01 16:06
This has been fixed with MiKTeX 2.9.6650.

**Closed by edocevoli** 2018-04-01 16:06 UTC
Labels: bug, linux, workaround, xetex

**Comment by fylimas** [comment] 2019-02-13 04:27
There are two new issues, namely, OS recognization error and font error, on macOS 10.14 with MiKTeX 2.9.6980 and the previous version of MiKTeX. These issues also exist on linux.

However, these issues do not exist for Texlive or mactex. I think there may be a hidden bug in MiKTeX.
Specifically, when I compile the file provided by @qiuzhu on macOS 10.14 with MiKTeX, it seems the ctex package finds SimSun (under windows) like fonts on the system, instead of Songti (under Mac) like fonts.
Then I specific the system with` \usepackage[fontset=mac]{ctex}`, ctex will find Songti like fonts under Mac. However, there is still errors that complains finding no fonts like Kaiti, which is caused by the fact that `Kaiti.ttc` is not in `/Library/Fonts`. In fact, it lie in `/System/Library/Assets/com_apple_MobileAsset_Font5` on macOS 10.14 Mojave or `/System/Library/Assets/com_apple_MobileAsset_Font4` on macOS 10.13 High Sierra.
By copying fonts to /Library/Fonts or modifies `~/Library/Application Support/MiKTeX/texmfs/config/fontconfig/config/localfonts2.conf` with
```
<?xml version="1.0"?>
<fontconfig>
<dir>/System/Library/Assets/com_apple_MobileAsset_Font5</dir>
</fontconfig>
```
for 10.14 Majove or 
```
<?xml version="1.0"?>
<fontconfig>
<dir>/System/Library/Assets/com_apple_MobileAsset_Font5</dir>
</fontconfig>
```
for 10.13 High Sierra, the fonts can be found correctly.

The following is a procedure on how to reproduce these errors.
file:
```
\documentclass{book}
\usepackage{ctex} % only works when comment this line
\usepackage{amsmath}
\usepackage{amsfonts}
\usepackage{amssymb}
\usepackage{graphicx}
\begin{document}
this is the demo for xelatex
Miktex 大法好
[E=mc^2]
\end{document}
```
errors:
`
/Users/fangyuanli/Library/Application Support/MiKTeX/texmfs/install/tex/latex/c
tex/fontset/ctex-fontset-windowsnew.def:110: Package fontspec Error: The font "
SimSun" cannot be found.
`
set system manually:
```
\documentclass{book}
\usepackage[fontset=mac]{ctex} % only works when comment this line
\usepackage{amsmath}
\usepackage{amsfonts}
\usepackage{amssymb}
\usepackage{graphicx}
\begin{document}
this is the demo for xelatex
Miktex 大法好
[E=mc^2]
\end{document}
```
errors:
`
/Users/fangyuanli/Library/Application Support/MiKTeX/texmfs/install/tex/latex/c
tex/fontset/ctex-fontset-macnew.def:56: Package fontspec Error: The font "Kaiti
 SC" cannot be found.
`
config fonts for MiKTeX:~/Library/Application Support/MiKTeX/texmfs/config/fontconfig/config/localfonts2.conf for 10.14 Mojave 
```
<?xml version="1.0"?>
<fontconfig>
<dir>/System/Library/Assets/com_apple_MobileAsset_Font5</dir>
</fontconfig>
```
Succeed.

More information can be found at issues (in Chinese):
* https://github.com/CTeX-org/ctex-kit/issues/340
* https://github.com/CTeX-org/ctex-kit/issues/313
Many thanks to @Liam0205 and @Liam0205.

**Comment by stone-zeng** [comment] 2019-06-26 15:58
This issue (KaiTi SC not found) is still there, in MiKTeX-XeTeX 2.9.6942 (0.999991) (MiKTeX 2.9.7050).

MWE:

```latex
\documentclass[10pt,a4paper]{ctexart}
\begin{document}
  你好
\end{document}
```

Error message:

```
Package fontspec Error: The font "Kaiti SC" cannot be found. }
```
