### ISSUE TITLE
DNF update error on Fedora 37

### ISSUE THREAD

**Issue by bzindovic** [MiKTeX/miktex#1330] opened 2023-05-12 08:47 UTC
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

When updating packages on Fedora 37 through dnf, I get the following error:
```
error: Verifying a signature using certificate D6BC243565B2087BC3F897C9277A7293F59E4889 (MiKTeX Packager <packager@miktex.org>):
  1. Certificiate 277A7293F59E4889 invalid: certificate is not alive
      because: The primary key is not live
      because: Expired on 2023-04-29T15:12:04Z
  2. Key 277A7293F59E4889 invalid: key is not alive
      because: The primary key is not live
      because: Expired on 2023-04-29T15:12:04Z
error: Verifying a signature using certificate D6BC243565B2087BC3F897C9277A7293F59E4889 (MiKTeX Packager <packager@miktex.org>):
  1. Certificiate 277A7293F59E4889 invalid: certificate is not alive
      because: The primary key is not live
      because: Expired on 2023-04-29T15:12:04Z
  2. Key 277A7293F59E4889 invalid: key is not alive
      because: The primary key is not live
      because: Expired on 2023-04-29T15:12:04Z
The GPG keys listed for the "MiKTeX Fedora 37" repository are already installed but they are not correct for this package.
Check that the correct key URLs are configured for this repository.. Failing package is: miktex-23.5-1.fc37.x86_64
 GPG Keys are configured as: 
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: GPG check FAILED

```
Has anyone encountered this?

**Comment by edocevoli** [comment] 2023-05-12 10:52
Duplicate of #1327

**Closed by edocevoli** 2023-05-12 10:52 UTC
