### ISSUE TITLE
Error with MiKTeX Console Check for updates

### ISSUE THREAD

**Issue by jefill41** [MiKTeX/miktex#572] opened 2020-06-30 08:21 UTC
Since the last update (29/6) I get this error message when I want to check for updates : 

GENERAL MIKTEX INFORMATION
ReportDate: 2020-06-30 10:20:56
CurrentVersion: 20.6
SetupDate: 2018-05-21 17:41:00
SetupVersion: 2.9
Configuration: Regular
GitInfo: 9cfc87b / 2020-06-29 20:05:02
OS: Windows 7 Ultimate, 64-bit, Service Pack 1, build 7601
SharedSetup: no
LinkTargetDirectory: L:\MiKTeX 2.9\miktex\bin\x64
PathOkay: yes
LastUpdateCheck: 2020-06-30 08:28:52
LastUpdate: 2020-06-30 08:29:10
LastUpdateDb: 2020-06-30 08:28:48
SystemAdmin: yes
RootPrivileges: no
AdminMode: no
Root0: C:\Users\Jean\AppData\Roaming\MiKTeX\2.9
Root1: C:\Users\Jean\AppData\Local\MiKTeX\2.9
Root2: L:\LocalTeXMF
Root3: L:\MiKTeX 2.9
Root4: C:\ProgramData\MiKTeX\2.9
Root5: C:\Program Files\MiKTeX 2.9
UserInstall: L:\MiKTeX 2.9
UserConfig: C:\Users\Jean\AppData\Roaming\MiKTeX\2.9
UserData: C:\Users\Jean\AppData\Local\MiKTeX\2.9
CommonInstall: C:\Program Files\MiKTeX 2.9
CommonConfig: C:\ProgramData\MiKTeX\2.9
CommonData: C:\ProgramData\MiKTeX\2.9
Invokers: 

ERROR DETAILS
Program: L:\MiKTeX 2.9\miktex\bin\x64\miktex-update.exe
Source: Libraries\MiKTeX\Core\Session\config.cpp:516
Error: Configuration error: no conversion from undefined configuration value to string.

**Comment by stehfun** [comment] 2020-06-30 08:28
Hi @all, same here:

-----
GENERAL MIKTEX INFORMATION
ReportDate: 2020-06-30 10:26:41
CurrentVersion: 20.6
SetupDate: 2018-04-15 00:09:00
SetupVersion: 2.9
Configuration: Regular
GitInfo: 9cfc87b / 2020-06-29 20:05:02
OS: Windows 10 Pro, 64-bit, build 19041
SharedSetup: yes
LinkTargetDirectory: C:\Program Files\MiKTeX 2.9\miktex\bin\x64
PathOkay: yes
LastUpdateCheckAdmin: 2020-06-30 10:07:42
LastUpdateAdmin: 2020-06-30 10:07:57
LastUpdateDbAdmin: 2020-06-30 10:07:40
LastUpdateCheck: 2020-06-19 20:48:27
LastUpdate: 2020-06-13 14:33:36
LastUpdateDb: 2020-06-19 20:48:26
SystemAdmin: yes
RootPrivileges: no
AdminMode: no
Root0: C:\Users\stefan\AppData\Roaming\MiKTeX\2.9
Root1: C:\Users\stefan\AppData\Local\MiKTeX\2.9
Root2: C:\ProgramData\MiKTeX\2.9
Root3: C:\Program Files\MiKTeX 2.9
UserInstall: C:\Users\stefan\AppData\Roaming\MiKTeX\2.9
UserConfig: C:\Users\stefan\AppData\Roaming\MiKTeX\2.9
UserData: C:\Users\stefan\AppData\Local\MiKTeX\2.9
CommonInstall: C:\Program Files\MiKTeX 2.9
CommonConfig: C:\ProgramData\MiKTeX\2.9
CommonData: C:\ProgramData\MiKTeX\2.9
Invokers: non-existing/explorer

The following issues were detected:
  1: major issue: User/administrator updates are out-of-sync.

ERROR DETAILS
Program: C:\Program Files\MiKTeX 2.9\miktex\bin\x64\miktex-console.exe
Source: Libraries\MiKTeX\Core\Session\config.cpp:516
Error: Configuration error: no conversion from undefined configuration value to string.
-----


Any ideas how to fix the updater?

**Comment by edocevoli** [comment] 2020-06-30 08:39
Duplicate of #571

**Closed by edocevoli** 2020-06-30 08:39 UTC
