### ISSUE TITLE
The package definition file could not be parsed

### ISSUE THREAD

**Issue by niklasholm** [MiKTeX/miktex#193] opened 2018-09-08 05:36 UTC
**Checklist:**
- [x] I am reporting a bug others will be able to reproduce
- [X] I have installed the latest MiKTeX updates
- [X] I have checked the MiKTeX log files

Trying to update packages through the MiKTeX Console, gets the following error. I've tried uninstalling and reinstalling MiKTeX from scratch.

```
MiKTeX Problem Report
Message: The package definition file could not be parsed.
Data: path="C:\Users\<>\AppData\Local\Temp\mik99735\bxorigcapt.tpm", column="1024", line="2"
Source: Libraries\MiKTeX\PackageManager\TpmParser.cpp
Line: 339
MiKTeX: 2.9
OS: Windows 7 Enterprise, 64-bit, Service Pack 1, build 7601
Invokers: explorer
SystemAdmin: no
PowerUser: no
Root0: C:\Users\<>\AppData\Roaming\MiKTeX\2.9
Root1: C:\Users\<>\AppData\Local\MiKTeX\2.9
Root2: C:\Users\<>\texmf
Root3: C:\Users\<>\AppData\Local\Programs\MiKTeX 2.9
Root4: C:\ProgramData\MiKTeX\2.9
Root5: C:\Program Files\MiKTeX 2.9
UserInstall: C:\Users\<>\AppData\Local\Programs\MiKTeX 2.9
UserConfig: C:\Users\<>\AppData\Roaming\MiKTeX\2.9
UserData: C:\Users\<>\AppData\Local\MiKTeX\2.9
CommonInstall: C:\Program Files\MiKTeX 2.9
CommonConfig: C:\ProgramData\MiKTeX\2.9
CommonData: C:\ProgramData\MiKTeX\2.9
```

**Comment by edocevoli** [comment] 2018-09-08 07:49
Duplicate of MiKTeX/miktex-packaging#48

**Closed** 2018-09-08 07:49 UTC
Labels: duplicate
