### ISSUE TITLE
PackageManager error with portable MiKTeX

### ISSUE THREAD

**Issue by zohooo** [MiKTeX/miktex#158] opened 2018-07-06 07:49 UTC
Checklist:
- [x] I am reporting a bug others will be able to reproduce
- [x] I have installed the latest MiKTeX updates
- [x] I have checked the MiKTeX log files
----
1. Download `miktex-portable-2.9.6753.exe` and extract it on my Windows 7
2. Click `miktex-portable.cmd` and then start Terminal from tray icon menu
3. Run `mpm --update` to get latest miktex packages 
4. Try to run `mpm --require=@miktex-pkg.txt` command and get the following error
````
Sorry, but "MiKTeX Package Manager" did not succeed.

The log file hopefully contains the information to get MiKTeX going again:

  D:/software/miktex/miktex6753/texmfs/data/miktex/log/mpmcli.log

You may want to visit the MiKTeX project page, if you need help.
````
`mpmcli.log` file
````
2018-07-06 15:30:06,279+0800 INFO  mpmcli - starting: mpmcli 2.9.6727 (MiKTeX 2.9.6730)
2018-07-06 15:30:06,279+0800 INFO  mpmcli - Operating on the private (per-user) MiKTeX setup
2018-07-06 15:30:06,302+0800 FATAL mpmcli - MiKTeX encountered an internal error.
2018-07-06 15:30:06,302+0800 FATAL mpmcli - Info: 
2018-07-06 15:30:06,302+0800 FATAL mpmcli - Source: Libraries\MiKTeX\PackageManager\PackageManagerImpl.cpp
2018-07-06 15:30:06,302+0800 FATAL mpmcli - Line: 676
````

**Comment by edocevoli** [comment] 2018-07-06 07:53
Please attach `miktex-pkg.txt`.

**Comment by zohooo** [comment] 2018-07-06 07:55
miktex-pkg.txt
````
aastex
achemso
adjustbox
algorithms
apa
apacite
arabtex
arev
beamer
beamerarticle
bera
bezos
bibtopic
booktabs
braille
cases
ccfonts
cjk
cjkpunct
cmbright
collectbox
colortbl
comment
covington
csquotes
ctex
dinbrief
dtk
eco
elsarticle
elsevier
enumitem
environ
esint
eso-pic
etoolbox
europecv
extarrows
extsizes
fancybox
fancyhdr
fancyvrb
filehook
fontawesome
fourier
g-brief
ieeetran
ifoddpage
ifsym
jurabib
kluwer
koma-script
l3kernel
l3packages
lipsum
listings
luxi
manfnt
mathtools
memoir
mhchem
moderncv
mptopdf
ms
mwe
mwcls
natbib
nomencl
ntheorem
paper
pdfpages
pdfscreen
pdfslide
pgf
pgfplots
plgraph
powerdot
prettyref
preview
revtex
rotating
rotfloat
seminar
setspace
simplecv
soul
stix
spie
subfig
tabu
tcolorbox
tex-gyre
tex-gyre-math
texpower
textpos
tipa
titlesec
translator
trimspaces
tufte-latex
tugboat
ulem
units
url
wasy
wasysym
wrapfig
xargs
xcolor
xcolor
xecjk
zhmetrics
zhnumber
````

**Comment by edocevoli** [comment] 2018-07-06 08:29
There is already an issue which describes the problem.

**Comment by edocevoli** [comment] 2018-07-06 08:30
Duplicate of #36

**Closed by edocevoli** 2018-07-06 08:30 UTC
