### ISSUE TITLE
Different indentation behaviors for MikTeX and TeXLive when involving two adjacent environments

### ISSUE THREAD

**Issue by github-young** [MiKTeX/miktex#1577] opened 2024-12-31 02:59 UTC
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

## Minimum working example

```tex
\documentclass{article}

\begin{document}
% indentation is different for MikTeX 4.11 (24.4) and TeXLive
{
\begin{center} % this environment is the key to reproduce this issue
  MikTeX
\end{center}
}
{\setlength{\parindent}{3em} % Expected an indent for the "I hereby declare..." sentence
I hereby declare that I am the sole author of the thesis.\\

\par This is a random sentence.
}

\end{document}
```

## Description

In my opinion, an indentation is expected before the sentence `I hereby declare that...`. It is true for TeXLive, but not for MikTeX, as shown in the following image:

![图片](https://github.com/user-attachments/assets/5f80e167-0d06-428a-ab97-68a27a44d8b8)

## Upload report
[miktex-report.txt](https://github.com/user-attachments/files/18278967/miktex-report.txt)

**Comment by edocevoli** [comment] 2024-12-31 13:49
I can reproduce the problem with TeX Live. See the attached PDF.
[test.pdf](https://github.com/user-attachments/files/18281862/test.pdf)
[test.log](https://github.com/user-attachments/files/18281875/test.log)
Closing this ticket because it is not MiKTeX-specific.

**Closed by edocevoli** 2024-12-31 13:49 UTC
