### ISSUE TITLE
Miktex console doesn't work

### ISSUE THREAD

**Issue by youth0820** [MiKTeX/miktex#284] opened 2019-03-23 05:38 UTC
I have just installed the Miktex. And then I opened the Miktex console(admin), but it doesn't react. And I restarted the computer and tried again but it didn't work again. Until now, I have never opened it successfully once. Help!!!!

**Comment by edocevoli** [comment] 2019-03-23 08:23
Duplicate of #239

**Closed by edocevoli** 2019-03-23 08:23 UTC
Labels: duplicate
