### ISSUE TITLE
MiKTeX no longer supports Arabic language

### ISSUE THREAD

**Issue by Basmah1961** [MiKTeX/miktex#994] opened 2021-12-09 15:10 UTC
Since MiKTeX 21.12, XeLaTeX does not seem to work well with Arabic language. It simply crashes. The issue is reported for polyglossia package, but it seems to me it is related to MiKTeX 21.12 rather than polyglossia 

[https://github.com/reutenauer/polyglossia/issues/523#issue-1075449611](url)

**Comment by edocevoli** [comment] 2021-12-09 15:41
Duplicate of #984

**Closed by edocevoli** 2021-12-09 15:41 UTC
