### ISSUE TITLE
MikTex: high cpu/power usage

### ISSUE THREAD

**Issue by jpmct** [MiKTeX/miktex#602] opened 2020-08-17 18:30 UTC
There seemed to be a problem using MikTex so I uninstalled and reinstalled (basic-miktex-20.6.29-x64). 

The only issue of note after reinstalling was the warning:
initexmf: warning: The lualatex executable could not be found.

It appears that MikTex was running and there was no need to reinstall, it was just taking a long time.
![att01](https://user-images.githubusercontent.com/69814021/90430652-be0b2c00-e0bf-11ea-8c4d-15ab922a7b88.png)
![att02](https://user-images.githubusercontent.com/69814021/90430660-c19eb300-e0bf-11ea-814e-77bd3b3c6200.png)
![att03](https://user-images.githubusercontent.com/69814021/90430666-c4010d00-e0bf-11ea-8d16-e5609fc848d2.png)

In fact, the problem seems to be that even for a straightforward .tex file there is a high CPU/power usage with the message "not responding":

att01,png:  when open miktex a background process for several minutes, high CPU/power usage
att02.png: when running
att03.png: when opening even a relatively straightforward .tex file with the message "not responding"

The pdf file is eventually generated but only after several minutes.

I have run other programs with no particular memory issues, for example Maple.

Any help, insight appreciated

**Comment by edocevoli** [comment] 2020-08-17 18:47
Thank you please expand the not-responding app so that we can see the spawned sub-processes.

**Comment by jpmct** [comment] 2020-08-17 19:12
It appears the spawned sub-process is the .tex file
att04: 
Thanks
    On Monday, 17 August 2020, 19:48:05 BST, Christian Schenk <notifications@github.com> wrote:  
 
 


Thank you please expand the not-responding app so that we can see the spawned sub-processes.

**Comment by jpmct** [comment] 2020-08-17 19:23
I don't know if it is significant but MikTex doesn't appear to be installed in the directory
C: \Windows\ Program Files
but rather
C:\Windows \ Users \jpmct \ AppData \ Local
this is because I am only the user on my laptop and I chose to just install for the user jpmct


    On Monday, 17 August 2020, 19:48:05 BST, Christian Schenk <notifications@github.com> wrote:  
 
 


Thank you please expand the not-responding app so that we can see the spawned sub-processes.

**Comment by edocevoli** [comment] 2020-08-18 06:26
Please actually attach the screenshot(s) to this issue.

**Comment by jpmct** [comment] 2020-08-18 08:19
As requested




    On Tuesday, 18 August 2020, 07:27:11 BST, Christian Schenk <notifications@github.com> wrote:  
 
 


Please actually attach the screenshot(s) to this issue.

**Comment by edocevoli** [comment] 2020-08-18 08:26
Please stop replying to emails send by GitHub. Instead, visit the issue page: https://github.com/MiKTeX/miktex/issues/602.

**Comment by jpmct** [comment] 2020-08-18 09:42
As requested: Though I'm not sure how useful this information is since when I run TeXworks, it hangs as a background process and when runs as an application it is fine until I create some latex commands and press enter and which point it hangs again.

I'm not sure at what point the problem occurred but I have downloaded ubuntu 20.04 LTS on WSL.

![att05](https://user-images.githubusercontent.com/69814021/90497096-9909ce00-e13e-11ea-93c7-04fb9d095f57.png)

**Comment by edocevoli** [comment] 2020-08-18 09:51
Thank you. So it seems that there are now sub-processes involved. You simply edit your document and TeXworks hangs.

At the moment I have no idea why it hangs. And because I cannot reproduce it on my machine, it is not possible to provide a fix for this issue.

You can try the standalone TeXworks installer (see here: https://github.com/TeXworks/texworks/releases). Maybe this works better for you.

**Closed by edocevoli** 2020-08-18 09:51 UTC
