### ISSUE TITLE
SSL connect error, checking for updates fail, package installation fail, https://api2.miktex.org/hello inaccessible

### ISSUE THREAD

**Issue by Kadir321** [MiKTeX/miktex#1242] opened 2022-12-09 04:19 UTC
I cannot check for updates. I cannot install packages.
error: SSL connect error
code:35
URL:  https://api2.miktex.org/hello
Even from the browser, I can not access https://api2.miktex.org/hello
How can I install packages? please help.
Kadir

**Comment by Kadir321** [comment] 2022-12-09 04:20
error code=35   URL: https://api2.miktex.org/hello

**Comment by edocevoli** [comment] 2022-12-09 10:13
Duplicate of #1241

**Closed by edocevoli** 2022-12-09 10:13 UTC
