### ISSUE TITLE
Error message: remote package repository is outdated

### ISSUE THREAD

**Issue by TheGeeksWereRight** [MiKTeX/miktex#395] opened 2019-10-16 13:35 UTC
Hi all, 
I think this error occured in the past for many times (Jan. 2017, Oct. 2018, ...). The reason always was a bug that had to be fixed elsewhere?

**What I tried to do:**
Select a remote package repository from:
MiKTex Package Manager (Admin) >> Repository >> Change Package Repository

**What I expected to happen:**
Package Repository to be changed

**What happened instead**
I get an error message:
"The remote package repository is outdated. You have to choose another repository."
The same happens for many selected remote repositories from the list.

- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

**Comment by edocevoli** [comment] 2019-10-16 14:12
Duplicate of #392

**Closed by edocevoli** 2019-10-16 14:12 UTC
Labels: duplicate
