### ISSUE TITLE
Miktex console fails to open

### ISSUE THREAD

**Issue by Comfort1991** [MiKTeX/miktex#799] opened 2021-04-28 11:24 UTC
- [ ] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

A MiKTeX configuration file could not be loaded.
Data: error="invalid value definition", file="/home/duxee/.miktex/texmfs/config/miktex/config/miktex.ini", line="6"
Source: Libraries/MiKTeX/Core/Cfg/Cfg.cpp:1057
A MiKTeX configuration file could not be loaded.
Info: error="invalid value definition", file="/home/duxee/.miktex/texmfs/config/miktex/config/miktex.ini", line="6"
Source: Libraries/MiKTeX/Core/Cfg/Cfg.cpp
Line: 1057

Sorry, but "MiKTeX Configuration Utility" did not succeed.
log4cxx: No appender could be found for logger (initexmf).
log4cxx: Please initialize the log4cxx system properly.

**Comment by edocevoli** [comment] 2021-04-28 14:43
Duplicate of #290

**Closed by edocevoli** 2021-04-28 14:43 UTC
