### ISSUE TITLE
Problems with the MikTEx configuration file

### ISSUE THREAD

**Issue by gdistiller** [MiKTeX/miktex#349] opened 2019-08-07 11:09 UTC
Hi, I recently upgraded my pc to Windows 10 and installed Miktex 2.9. It initially worked but then something went wrong and I kept on getting an error message that said something to do with not being able to load the configuration file. Whatever I tried to do gave the error, for example if I checked for updates I got an error and if I clicked on the packages link the console shuts down and gave me an error. I uninstalled and reinstalled which seemed to fix the problem and I have used it fine for the past 2 to 3 weeks. However now the same thing has happened again and I have no idea what could have caused it. I can obviously uninstall and reinstall again, but since this is the 2nd time it has happened I thought it worth trying to find out what is going on. The full error message is below, I have also noticed that now there are no directories showing up either under Settings -> Directories:

GENERAL MIKTEX INFORMATION
Date: 2019-08-07 13:05:56
MiKTeX: 2.9.7050
OS: Windows 10 Enterprise, 64-bit, build 17134
SharedSetup: no
LinkTargetDirectory: C:\Users\01376436\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64
PathOkay: yes
LastUpdateCheck: 2019-07-18 09:50:21
LastUpdate: 2019-07-18 09:48:27
SystemAdmin: yes
RootPrivileges: no
AdminMode: no
Root0: C:\Users\01376436\AppData\Roaming\MiKTeX\2.9
Root1: C:\Users\01376436\AppData\Local\MiKTeX\2.9
Root2: C:\localtexmf
Root3: C:\Users\01376436\AppData\Local\Programs\MiKTeX 2.9
Root4: C:\ProgramData\MiKTeX\2.9
Root5: C:\Program Files\MiKTeX 2.9
UserInstall: C:\Users\01376436\AppData\Local\Programs\MiKTeX 2.9
UserConfig: C:\Users\01376436\AppData\Roaming\MiKTeX\2.9
UserData: C:\Users\01376436\AppData\Local\MiKTeX\2.9
CommonInstall: C:\Program Files\MiKTeX 2.9
CommonConfig: C:\ProgramData\MiKTeX\2.9
CommonData: C:\ProgramData\MiKTeX\2.9
Invokers: non-existing/explorer

ERROR DETAILS
Program: C:\Users\01376436\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\miktex-console.exe
Source: Libraries\MiKTeX\Core\Cfg\Cfg.cpp:1052
Error: A MiKTeX configuration file could not be loaded.
Details: 
  file: C:\Users\01376436\AppData\Local\Programs\MiKTeX 2.9\miktex/config\package-manifests.ini
  line: 180650
  error: invalid value definition

Thanks in advance.

Greg

**Comment by edocevoli** [comment] 2019-08-07 14:19
This is a duplicate of a closed issue.

**Closed by edocevoli** 2019-08-07 14:19 UTC
