### ISSUE TITLE
Admin mode required but not accessible

### ISSUE THREAD

**Issue by projekter** [MiKTeX/miktex#419] opened 2019-11-15 07:49 UTC
I tried to run updates via the MikTeX console. Since the last time I updated is already past a couple of week, I believe there must be quite a few. However (as it was in pre-console times with the two-stage update process), the console reports only three of them (`miktex-harftex-bin-x64-2.9`, `ifetex` and `ifxetex`) which are all about to be removed. All three of them have a comment in the last column: `removal only possible in admin mode`. I can't check them and can't run those updates.
Previously, I had a shared MikTeX installation and did every update in admin mode, but recently, I noted that updating the formats (due to [this](https://github.com/MiKTeX/miktex-packaging/issues/131#issuecomment-541309319) issue) did not increase the version number. I thought that this might be a shared/single user related problem and chose "Reset personal MikTeX configuration" in the Cleanup section of the console, as I really don't need a shared installation. After that, obviously my installation was set to be user-mode only, as I was never again asked to enter admin mode and indeed every packaged changed its "Installed by" entry to "User".
So now the problem is that I don't have an admin mode (starting the console with `--admin` parameter confirms this: It aborts saying `Option --admin only makes sense for a shared MiKTeX setup.`), but in order to uninstall those three packages and subsequently (I hope) being able to do updates again, I need to enter the admin mode.
It looks like the "Reset personal MikTeX configuration" has somehow put my installation in an inconsistent state. Rebuilding the FNDB before the update did not help.

`initexmf --report`:
```
initexmf: warning: Option --admin should be specified when running this program with administrator privileges
Date: 2019-11-15 08:44:12
MiKTeX: 2.9.7200 NEXT
OS: Windows 10 Pro, 64-bit, build 18362
SharedSetup: no
LinkTargetDirectory: C:\Program Files\MiKTeX 2.9\miktex\bin\x64
PathOkay: yes
LastUpdateCheck: 2019-11-15 08:33:09
LastUpdate: not yet
SystemAdmin: yes
RootPrivileges: yes
AdminMode: no
Root0: C:\Users\Benni\AppData\Roaming\MiKTeX\2.9
Root1: C:\Users\Benni\AppData\Local\MiKTeX\2.9
Root2: D:\Dokumente\TeX
Root3: C:\ProgramData\MiKTeX\2.9
Root4: C:\Program Files\MiKTeX 2.9
UserInstall: C:\Users\Benni\AppData\Roaming\MiKTeX\2.9
UserConfig: C:\Users\Benni\AppData\Roaming\MiKTeX\2.9
UserData: C:\Users\Benni\AppData\Local\MiKTeX\2.9
CommonInstall: C:\Program Files\MiKTeX 2.9
CommonConfig: C:\ProgramData\MiKTeX\2.9
CommonData: C:\ProgramData\MiKTeX\2.9
```

- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

**Comment by edocevoli** [comment] 2019-11-15 09:26
Seems that there are some relicts from the previous installation. To find out:

```
reg export HKLM\Software\MiKTeX.org hklm.txt
reg export HKCU\Software\MiKTeX.org hkcu.txt
dir /s "C:\Program Files\MiKTeX 2.9" > common-install.txt
dir /s "C:\ProgramData\MiKTeX\2.9" > common-config.txt
```

**Comment by projekter** [comment] 2019-11-15 09:33
On this system, there were no previous installations. The HKLM keys do not exist.
[exports.zip](https://github.com/MiKTeX/miktex/files/3850790/exports.zip)

**Comment by edocevoli** [comment] 2019-11-15 10:23
Sorry, I was a little bit confused. Please attach the relevant package manager files:

```
%APPDATA%\MiKTeX\2.9\miktex\config\mpm.ini
%APPDATA%\MiKTeX\2.9\miktex\config\packages.ini
%APPDATA%\MiKTeX\2.9\miktex\config\package-manifests.ini
```

**Comment by projekter** [comment] 2019-11-15 11:03
[config.zip](https://github.com/MiKTeX/miktex/files/3851173/config.zip)

**Comment by edocevoli** [comment] 2019-11-15 12:11
The config file `packages.ini` is almost empty which means that no packages are installed and the updater has nothing to do,

It should be possible to manually install missing packages. This seems to be the only work-around for this broken MiKTeX installation.

**Comment by projekter** [comment] 2019-11-15 12:26
Actually, I have almost the complete CTAN installed. However, they all reside in the `Program Files\...\config` instead of the `%APPDATA%` section (this `packages.ini` has about 15000 lines). I would say this means they are all admin-mode installed packages, quite in contrast to what the MikTeX console say, which reports them all as user mode. And in fact, I installed them in admin mode.
My point in reporting this was not so much my installation which out of all sudden seems to be broken, but that probably the "Reset personal MikTeX configuration" option in the console is buggy: To me, it seems to reset all user-mode configuration options (good) while at the same time tells MikTeX that actually, there is no admin configuration, i.e. no admin-mode installed packages, ... (bad). Still, all packages _were_ installed in admin mode and remain in the programs folder. But now, no MikTeX tool will ever start again in admin mode, and hence it is no longer possible to make any changes (or perhaps only removals are disallowed) to the packages. At least this is my reasoning so far.

**Comment by edocevoli** [comment] 2019-11-15 12:38
Since you said

> On this system, there were no previous installations. The HKLM keys do not exist.

I was under the impression that you have a pure user installation. It turns out that you once had a shared setup. Correct?

Somehow the HKLM key has been deleted and now the MiKTeX installation is broken.

**Comment by projekter** [comment] 2019-11-15 12:46
Exactly. When I installed some years ago, this was a shared setup. I never deliberatly made any non-admin changes, but I suppose I at least once forgot these, so that the format files were in fact user-managed. Hence, they were not affected by my usual system-level changes. I thought I could simply remove the few user-based entries using the "Reset personal MikTeX configuration" function, but it rather looks like it deleted anything that made MikTeX know it was a shared setup in the first place.

**Comment by edocevoli** [comment] 2019-11-15 12:47
I will try to reproduce the issue ("Reset personal MikTeX configuration" is broken).

It should be possible to restore the HKLM key. I will later post a `.reg` file.

**Comment by edocevoli** [comment] 2019-11-15 13:33
There is no problem with the latest MiKTeX version: `Reset personal MikTeX configuration` does not delete the HKLM key: the issue has been fixed with one of the latest MiKTeX updates.

You can restore the the HKLM key as follows:

```
reg add HKLM\Software\MiKTeX.org\MiKTeX\2.9\Core /v SharedSetup /d 1
reg add HKLM\Software\MiKTeX.org\MiKTeX\2.9\Core /v LastAdminMaintenance /d 1573824075
```

**Comment by projekter** [comment] 2019-11-15 13:36
Great, thanks! This looks a lot better.

**Comment by projekter** [comment] 2020-02-10 09:26
After I experienced a problem that MikTeX for some reason re-built format files in user mode (though I only performed package updates in admin mode), I again selected `Reset personal MikTeX configuration` and ended up again with precisely the same issue as before. Again, adding the registry keys solved the problems, but it looks like the button still deletes those keys. My MikTeX distribution was up-to-date (dated by today) before I performed the reset.

**Comment by edocevoli** [comment] 2020-02-10 10:03
If you run MiKTeX Console as MiKTeX user, it should not be possible to delete `HKLM` keys. You simply don't have the permissions.

**Comment by projekter** [comment] 2020-02-10 10:07
The Console itself has the permissions (from the OS perspective), as I don't use UAC restrictions. It is an application with administrator privileges, but runs in MikTeX user mode.

**Comment by edocevoli** [comment] 2020-02-10 10:10
Okay, thank you. Indeed, if you run elevated, then these `HKLM` keys will be deleted. It's a bug.

**Comment by projekter** [comment] 2020-02-10 10:16
The perhaps this is also related to another message (which I don't know whether it does any harm or not): All compilers give a warning, e.g., `lualatex-dev: warning: running with elevated privileges` (they themselves do not have an `--admin` switch). However, when some changes to the package repsitory, FNDB, ... occurred, the compiler calls `initexmf`, which then warns that `Option --admin should be specified when running this program with administrator privileges`. I now wonder if maybe at this stage `initexmf` might create some user-level configuration, although it could (should?) only modify the system-wide configuration. Perhaps introducing an `--admin` switch for the compilers that does nothing than passing it on to `initexmf` might give some control of this to the user, if you see the possibility of an issue.

**Comment by edocevoli** [comment] 2020-02-10 10:23
It is possible to run tools like `pdflatex` automatically in admin mode (if elevated):

```
initexmf --admin --set-config-value=[Core]AutoAdmin=t
```

**Comment by edocevoli** [comment] 2020-02-20 10:18
This has been fixed.

**Closed by edocevoli** 2020-02-20 10:18 UTC
Labels: bug
