### ISSUE TITLE
`\IfFileExists{nul:}` doesn't work on Windows, which breaks `ifplatform`

### ISSUE THREAD

**Issue by gpotter2** [MiKTeX/miktex#1012] opened 2022-01-03 22:10 UTC
Hi ! (first of all thanks a lot for MiKTeX, it's really awesome !)

The following snippet fails to build on Windows:
```tex
\IfFileExists{nul:}{
    hey
}{
    ho
}
```
and throws the following:

>Sorry, but pdflatex did not succeed for the following reason:
> MiKTeX cannot retrieve attributes for the file '.\nul:.tex'.

with in the logs:
```
2022-01-03 22:45:49,594+0100 ERROR pdflatex.core - Function: GetFileAttributesW
2022-01-03 22:45:49,594+0100 ERROR pdflatex.core - Result: 1251
2022-01-03 22:45:49,594+0100 ERROR pdflatex.core - Data: path=".\nul:.tex"
2022-01-03 22:45:49,594+0100 ERROR pdflatex.core - Source: Libraries\MiKTeX\Core\File\win\winFile.cpp:95
```

**This doesn't look too crazy** (IMHO).

The issue is that a smilar snippet is used in the decades-old `ifplatform` package over at https://github.com/wspr/will2e/blob/master/ifplatform/ifplatform.dtx#L290, in order to detect whether the OS is running Windows or not. This package [is currently packaged on miktex](https://miktex.org/packages/ifplatform) and [is used by some well-used packages like `minted`](https://github.com/gpoore/minted/blob/8951e422de4d06a65cf825c35805e6e10e61edbc/source/minted.sty#L42). The error breaks its functionality as it doesn't build on Windows and creates this compilation error (at least on my end).

Do you think that this should be fixed in Miktex, for instance by adding an additional check here:
https://github.com/MiKTeX/miktex/blob/3ac6ff32fa545171dcb168a60f3565a5b22064bf/Libraries/MiKTeX/Core/File/win/winFile.cpp#L71
or patched in the package itself (this option might be hard: I'm not sure how maintained the package is :///)

Thanks a lot for the help !

**Comment by edocevoli** [comment] 2022-01-04 07:34
Yes, this should be fixed in MiKTeX.

**Comment by edocevoli** [comment] 2022-01-04 12:33
Seems that this is not a bug. At least I was not able to reproduce it with the given info.

What I did:

Create `test.tex`:

```latex
\documentclass{article}
\begin{document}
\IfFileExists{nul:}{
    hey
}{
    ho
}
\end{document}
```

Run `pdflatex test.tex` which produces `test.pdf` containing `hey`.

**Closed by edocevoli** 2022-01-04 12:33 UTC
