### ISSUE TITLE
MiKTeX console with a non-ASCII character in the profil name

### ISSUE THREAD

**Issue by petiard** [MiKTeX/miktex#285] opened 2019-03-31 17:47 UTC
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

Hello

On my computer (Windows10 pro, 64 bits, MiKTeX 64 bits), I have 3 counts:
François as administrator
User1 as user
User2 as administrator

If I launch miktex-console from François, I have a message : "MiKTeX Console cannot be started" then the program fails.
If I launch miktex-console from User2, no problem: the program launchs the console and I can switch to Console-Admin.
If I launch miktex-console from User1: the program launchs the console and, if I want to switch to Console-Admin: if I try with User2, no problem ; if I try with François, same message "MiKTeX Console cannot be started".
So, I suspect the non-ASCII character "ç" in François to be the problem.
Best regards
François Pétiard

**Comment by edocevoli** [comment] 2019-03-31 18:26
Thank you. We are closing this ticket now because you havn't attached the log files yet.

**Closed by edocevoli** 2019-03-31 18:26 UTC

**Comment by petiard** [comment] 2019-03-31 19:03
There is no log file for François (in fact, there is a log file, but the last date is 3 february 2019).

I attach 3 log files.

François
[miktex-console_admin.log](https://github.com/MiKTeX/miktex/files/3027033/miktex-console_admin.log)
[miktex-console_User1.log](https://github.com/MiKTeX/miktex/files/3027034/miktex-console_User1.log)
[miktex-console_User2.log](https://github.com/MiKTeX/miktex/files/3027035/miktex-console_User2.log)

**Comment by edocevoli** [comment] 2019-03-31 20:16
Sorry, I mean the DbgView log (see #239).

**Comment by edocevoli** [comment] 2019-03-31 20:16
Duplicate of #239
